// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/session.proto

package com.google.bigtable.v2;

public interface CloseSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.CloseSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.bigtable.v2.CloseSessionRequest.CloseSessionReason reason = 1;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.google.bigtable.v2.CloseSessionRequest.CloseSessionReason reason = 1;</code>
   * @return The reason.
   */
  com.google.bigtable.v2.CloseSessionRequest.CloseSessionReason getReason();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
