// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/session.proto
// Protobuf Java Version: 4.33.6

package com.google.bigtable.v2;

@com.google.protobuf.Generated
public interface ClusterInformationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.ClusterInformation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cluster_id = 1;</code>
   * @return The clusterId.
   */
  java.lang.String getClusterId();
  /**
   * <code>string cluster_id = 1;</code>
   * @return The bytes for clusterId.
   */
  com.google.protobuf.ByteString
      getClusterIdBytes();

  /**
   * <code>string zone_id = 2;</code>
   * @return The zoneId.
   */
  java.lang.String getZoneId();
  /**
   * <code>string zone_id = 2;</code>
   * @return The bytes for zoneId.
   */
  com.google.protobuf.ByteString
      getZoneIdBytes();
}
