// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/bigtable.proto
// Protobuf Java Version: 4.33.6

package com.google.bigtable.v2;

/**
 *
 *
 * <pre>
 * Note: This API won't be generally available.
 * Request message for InferInternalTypeMetadata
 * </pre>
 *
 * Protobuf type {@code google.bigtable.v2.InferInternalTypeMetadataRequest}
 */
@com.google.protobuf.Generated
public final class InferInternalTypeMetadataRequest extends com.google.protobuf.GeneratedMessage
    implements
    // @@protoc_insertion_point(message_implements:google.bigtable.v2.InferInternalTypeMetadataRequest)
    InferInternalTypeMetadataRequestOrBuilder {
  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 6,
        /* suffix= */ "",
        "InferInternalTypeMetadataRequest");
  }

  // Use InferInternalTypeMetadataRequest.newBuilder() to construct.
  private InferInternalTypeMetadataRequest(
      com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private InferInternalTypeMetadataRequest() {
    tableName_ = "";
    appProfileId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.bigtable.v2.BigtableProto
        .internal_static_google_bigtable_v2_InferInternalTypeMetadataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.bigtable.v2.BigtableProto
        .internal_static_google_bigtable_v2_InferInternalTypeMetadataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.bigtable.v2.InferInternalTypeMetadataRequest.class,
            com.google.bigtable.v2.InferInternalTypeMetadataRequest.Builder.class);
  }

  public static final int TABLE_NAME_FIELD_NUMBER = 1;

  @SuppressWarnings("serial")
  private volatile java.lang.Object tableName_ = "";

  /**
   *
   *
   * <pre>
   * Required. The unique name of the requested table.
   * Values are of the form
   * `projects/{project}/instances/{instance}/tables/{table}`.
   * </pre>
   *
   * <code>
   * string table_name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The tableName.
   */
  @java.lang.Override
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }

  /**
   *
   *
   * <pre>
   * Required. The unique name of the requested table.
   * Values are of the form
   * `projects/{project}/instances/{instance}/tables/{table}`.
   * </pre>
   *
   * <code>
   * string table_name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The bytes for tableName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APP_PROFILE_ID_FIELD_NUMBER = 5;

  @SuppressWarnings("serial")
  private volatile java.lang.Object appProfileId_ = "";

  /**
   *
   *
   * <pre>
   * This API only accepts the empty value of app_profile_id.
   * </pre>
   *
   * <code>string app_profile_id = 5;</code>
   *
   * @return The appProfileId.
   */
  @java.lang.Override
  public java.lang.String getAppProfileId() {
    java.lang.Object ref = appProfileId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appProfileId_ = s;
      return s;
    }
  }

  /**
   *
   *
   * <pre>
   * This API only accepts the empty value of app_profile_id.
   * </pre>
   *
   * <code>string app_profile_id = 5;</code>
   *
   * @return The bytes for appProfileId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAppProfileIdBytes() {
    java.lang.Object ref = appProfileId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      appProfileId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROWS_LIMIT_FIELD_NUMBER = 3;
  private int rowsLimit_ = 0;

  /**
   *
   *
   * <pre>
   * The API will scan the first `rows_limit` rows in the table. The limit must
   * be greater than 0 and less than or equal to 1000, otherwise the request
   * will fail.
   * </pre>
   *
   * <code>int32 rows_limit = 3;</code>
   *
   * @return The rowsLimit.
   */
  @java.lang.Override
  public int getRowsLimit() {
    return rowsLimit_;
  }

  public static final int COLUMNS_PER_ROW_LIMIT_FIELD_NUMBER = 4;
  private int columnsPerRowLimit_ = 0;

  /**
   *
   *
   * <pre>
   * The API will scan the first `columns_per_row_limit` columns in each row.
   * The limit must be greater than 0 and less than or equal to 1000, otherwise
   * the request will fail.
   * </pre>
   *
   * <code>int32 columns_per_row_limit = 4;</code>
   *
   * @return The columnsPerRowLimit.
   */
  @java.lang.Override
  public int getColumnsPerRowLimit() {
    return columnsPerRowLimit_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tableName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, tableName_);
    }
    if (rowsLimit_ != 0) {
      output.writeInt32(3, rowsLimit_);
    }
    if (columnsPerRowLimit_ != 0) {
      output.writeInt32(4, columnsPerRowLimit_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(appProfileId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, appProfileId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tableName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, tableName_);
    }
    if (rowsLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, rowsLimit_);
    }
    if (columnsPerRowLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream.computeInt32Size(4, columnsPerRowLimit_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(appProfileId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, appProfileId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.bigtable.v2.InferInternalTypeMetadataRequest)) {
      return super.equals(obj);
    }
    com.google.bigtable.v2.InferInternalTypeMetadataRequest other =
        (com.google.bigtable.v2.InferInternalTypeMetadataRequest) obj;

    if (!getTableName().equals(other.getTableName())) return false;
    if (!getAppProfileId().equals(other.getAppProfileId())) return false;
    if (getRowsLimit() != other.getRowsLimit()) return false;
    if (getColumnsPerRowLimit() != other.getColumnsPerRowLimit()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    hash = (37 * hash) + APP_PROFILE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAppProfileId().hashCode();
    hash = (37 * hash) + ROWS_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getRowsLimit();
    hash = (37 * hash) + COLUMNS_PER_ROW_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getColumnsPerRowLimit();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      com.google.bigtable.v2.InferInternalTypeMetadataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   *
   *
   * <pre>
   * Note: This API won't be generally available.
   * Request message for InferInternalTypeMetadata
   * </pre>
   *
   * Protobuf type {@code google.bigtable.v2.InferInternalTypeMetadataRequest}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.bigtable.v2.InferInternalTypeMetadataRequest)
      com.google.bigtable.v2.InferInternalTypeMetadataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.bigtable.v2.BigtableProto
          .internal_static_google_bigtable_v2_InferInternalTypeMetadataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.bigtable.v2.BigtableProto
          .internal_static_google_bigtable_v2_InferInternalTypeMetadataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.bigtable.v2.InferInternalTypeMetadataRequest.class,
              com.google.bigtable.v2.InferInternalTypeMetadataRequest.Builder.class);
    }

    // Construct using com.google.bigtable.v2.InferInternalTypeMetadataRequest.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tableName_ = "";
      appProfileId_ = "";
      rowsLimit_ = 0;
      columnsPerRowLimit_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.bigtable.v2.BigtableProto
          .internal_static_google_bigtable_v2_InferInternalTypeMetadataRequest_descriptor;
    }

    @java.lang.Override
    public com.google.bigtable.v2.InferInternalTypeMetadataRequest getDefaultInstanceForType() {
      return com.google.bigtable.v2.InferInternalTypeMetadataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.bigtable.v2.InferInternalTypeMetadataRequest build() {
      com.google.bigtable.v2.InferInternalTypeMetadataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.bigtable.v2.InferInternalTypeMetadataRequest buildPartial() {
      com.google.bigtable.v2.InferInternalTypeMetadataRequest result =
          new com.google.bigtable.v2.InferInternalTypeMetadataRequest(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.bigtable.v2.InferInternalTypeMetadataRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tableName_ = tableName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.appProfileId_ = appProfileId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rowsLimit_ = rowsLimit_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.columnsPerRowLimit_ = columnsPerRowLimit_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.bigtable.v2.InferInternalTypeMetadataRequest) {
        return mergeFrom((com.google.bigtable.v2.InferInternalTypeMetadataRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.bigtable.v2.InferInternalTypeMetadataRequest other) {
      if (other == com.google.bigtable.v2.InferInternalTypeMetadataRequest.getDefaultInstance())
        return this;
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getAppProfileId().isEmpty()) {
        appProfileId_ = other.appProfileId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getRowsLimit() != 0) {
        setRowsLimit(other.getRowsLimit());
      }
      if (other.getColumnsPerRowLimit() != 0) {
        setColumnsPerRowLimit(other.getColumnsPerRowLimit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                tableName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 24:
              {
                rowsLimit_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
            case 32:
              {
                columnsPerRowLimit_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
            case 42:
              {
                appProfileId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 42
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private java.lang.Object tableName_ = "";

    /**
     *
     *
     * <pre>
     * Required. The unique name of the requested table.
     * Values are of the form
     * `projects/{project}/instances/{instance}/tables/{table}`.
     * </pre>
     *
     * <code>
     * string table_name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return The tableName.
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     *
     *
     * <pre>
     * Required. The unique name of the requested table.
     * Values are of the form
     * `projects/{project}/instances/{instance}/tables/{table}`.
     * </pre>
     *
     * <code>
     * string table_name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return The bytes for tableName.
     */
    public com.google.protobuf.ByteString getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     *
     *
     * <pre>
     * Required. The unique name of the requested table.
     * Values are of the form
     * `projects/{project}/instances/{instance}/tables/{table}`.
     * </pre>
     *
     * <code>
     * string table_name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @param value The tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableName(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      tableName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     *
     *
     * <pre>
     * Required. The unique name of the requested table.
     * Values are of the form
     * `projects/{project}/instances/{instance}/tables/{table}`.
     * </pre>
     *
     * <code>
     * string table_name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return This builder for chaining.
     */
    public Builder clearTableName() {
      tableName_ = getDefaultInstance().getTableName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    /**
     *
     *
     * <pre>
     * Required. The unique name of the requested table.
     * Values are of the form
     * `projects/{project}/instances/{instance}/tables/{table}`.
     * </pre>
     *
     * <code>
     * string table_name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @param value The bytes for tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      tableName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object appProfileId_ = "";

    /**
     *
     *
     * <pre>
     * This API only accepts the empty value of app_profile_id.
     * </pre>
     *
     * <code>string app_profile_id = 5;</code>
     *
     * @return The appProfileId.
     */
    public java.lang.String getAppProfileId() {
      java.lang.Object ref = appProfileId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appProfileId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     *
     *
     * <pre>
     * This API only accepts the empty value of app_profile_id.
     * </pre>
     *
     * <code>string app_profile_id = 5;</code>
     *
     * @return The bytes for appProfileId.
     */
    public com.google.protobuf.ByteString getAppProfileIdBytes() {
      java.lang.Object ref = appProfileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        appProfileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     *
     *
     * <pre>
     * This API only accepts the empty value of app_profile_id.
     * </pre>
     *
     * <code>string app_profile_id = 5;</code>
     *
     * @param value The appProfileId to set.
     * @return This builder for chaining.
     */
    public Builder setAppProfileId(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      appProfileId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     *
     *
     * <pre>
     * This API only accepts the empty value of app_profile_id.
     * </pre>
     *
     * <code>string app_profile_id = 5;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearAppProfileId() {
      appProfileId_ = getDefaultInstance().getAppProfileId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    /**
     *
     *
     * <pre>
     * This API only accepts the empty value of app_profile_id.
     * </pre>
     *
     * <code>string app_profile_id = 5;</code>
     *
     * @param value The bytes for appProfileId to set.
     * @return This builder for chaining.
     */
    public Builder setAppProfileIdBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      appProfileId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int rowsLimit_;

    /**
     *
     *
     * <pre>
     * The API will scan the first `rows_limit` rows in the table. The limit must
     * be greater than 0 and less than or equal to 1000, otherwise the request
     * will fail.
     * </pre>
     *
     * <code>int32 rows_limit = 3;</code>
     *
     * @return The rowsLimit.
     */
    @java.lang.Override
    public int getRowsLimit() {
      return rowsLimit_;
    }

    /**
     *
     *
     * <pre>
     * The API will scan the first `rows_limit` rows in the table. The limit must
     * be greater than 0 and less than or equal to 1000, otherwise the request
     * will fail.
     * </pre>
     *
     * <code>int32 rows_limit = 3;</code>
     *
     * @param value The rowsLimit to set.
     * @return This builder for chaining.
     */
    public Builder setRowsLimit(int value) {

      rowsLimit_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    /**
     *
     *
     * <pre>
     * The API will scan the first `rows_limit` rows in the table. The limit must
     * be greater than 0 and less than or equal to 1000, otherwise the request
     * will fail.
     * </pre>
     *
     * <code>int32 rows_limit = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearRowsLimit() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rowsLimit_ = 0;
      onChanged();
      return this;
    }

    private int columnsPerRowLimit_;

    /**
     *
     *
     * <pre>
     * The API will scan the first `columns_per_row_limit` columns in each row.
     * The limit must be greater than 0 and less than or equal to 1000, otherwise
     * the request will fail.
     * </pre>
     *
     * <code>int32 columns_per_row_limit = 4;</code>
     *
     * @return The columnsPerRowLimit.
     */
    @java.lang.Override
    public int getColumnsPerRowLimit() {
      return columnsPerRowLimit_;
    }

    /**
     *
     *
     * <pre>
     * The API will scan the first `columns_per_row_limit` columns in each row.
     * The limit must be greater than 0 and less than or equal to 1000, otherwise
     * the request will fail.
     * </pre>
     *
     * <code>int32 columns_per_row_limit = 4;</code>
     *
     * @param value The columnsPerRowLimit to set.
     * @return This builder for chaining.
     */
    public Builder setColumnsPerRowLimit(int value) {

      columnsPerRowLimit_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    /**
     *
     *
     * <pre>
     * The API will scan the first `columns_per_row_limit` columns in each row.
     * The limit must be greater than 0 and less than or equal to 1000, otherwise
     * the request will fail.
     * </pre>
     *
     * <code>int32 columns_per_row_limit = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearColumnsPerRowLimit() {
      bitField0_ = (bitField0_ & ~0x00000008);
      columnsPerRowLimit_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.bigtable.v2.InferInternalTypeMetadataRequest)
  }

  // @@protoc_insertion_point(class_scope:google.bigtable.v2.InferInternalTypeMetadataRequest)
  private static final com.google.bigtable.v2.InferInternalTypeMetadataRequest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.bigtable.v2.InferInternalTypeMetadataRequest();
  }

  public static com.google.bigtable.v2.InferInternalTypeMetadataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InferInternalTypeMetadataRequest> PARSER =
      new com.google.protobuf.AbstractParser<InferInternalTypeMetadataRequest>() {
        @java.lang.Override
        public InferInternalTypeMetadataRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<InferInternalTypeMetadataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InferInternalTypeMetadataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.bigtable.v2.InferInternalTypeMetadataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
