// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/session.proto
// Protobuf Java Version: 4.33.6

package com.google.bigtable.v2;

@com.google.protobuf.Generated
public interface OpenTableRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.OpenTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table_name = 1;</code>
   *
   * @return The tableName.
   */
  java.lang.String getTableName();

  /**
   * <code>string table_name = 1;</code>
   *
   * @return The bytes for tableName.
   */
  com.google.protobuf.ByteString getTableNameBytes();

  /**
   * <code>string app_profile_id = 2;</code>
   *
   * @return The appProfileId.
   */
  java.lang.String getAppProfileId();

  /**
   * <code>string app_profile_id = 2;</code>
   *
   * @return The bytes for appProfileId.
   */
  com.google.protobuf.ByteString getAppProfileIdBytes();

  /**
   * <code>.google.bigtable.v2.OpenTableRequest.Permission permission = 3;</code>
   *
   * @return The enum numeric value on the wire for permission.
   */
  int getPermissionValue();

  /**
   * <code>.google.bigtable.v2.OpenTableRequest.Permission permission = 3;</code>
   *
   * @return The permission.
   */
  com.google.bigtable.v2.OpenTableRequest.Permission getPermission();
}
