// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/peer_info.proto

package com.google.bigtable.v2;

/**
 * <pre>
 * PeerLoadInfo contains information about the peer that can be used for
 * load balancing.
 * (-- Next ID: 8 --)
 * </pre>
 *
 * Protobuf type {@code google.bigtable.v2.PeerLoadInfo}
 */
public final class PeerLoadInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.bigtable.v2.PeerLoadInfo)
    PeerLoadInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PeerLoadInfo.newBuilder() to construct.
  private PeerLoadInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PeerLoadInfo() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PeerLoadInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.bigtable.v2.PeerInfoProto.internal_static_google_bigtable_v2_PeerLoadInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.bigtable.v2.PeerInfoProto.internal_static_google_bigtable_v2_PeerLoadInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.bigtable.v2.PeerLoadInfo.class, com.google.bigtable.v2.PeerLoadInfo.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_ = 0;
  /**
   * <pre>
   * PeerLoadInfo messages with different versions cannot be safely compared.
   * For example, one version of the logic may result in a lower expected,
   * latency, but that doesn't mean that the client should only send traffic to
   * the "faster" peers that use that version.
   * </pre>
   *
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int EXPECTED_LATENCY_MS_FIELD_NUMBER = 2;
  private float expectedLatencyMs_ = 0F;
  /**
   * <pre>
   * Peer's best guess as to how long requests will take. This may be noisy.
   * This does not include network latency.
   * </pre>
   *
   * <code>float expected_latency_ms = 2;</code>
   * @return The expectedLatencyMs.
   */
  @java.lang.Override
  public float getExpectedLatencyMs() {
    return expectedLatencyMs_;
  }

  public static final int WEIGHT_FIELD_NUMBER = 3;
  private float weight_ = 0F;
  /**
   * <pre>
   * Higher weight means that the peer is less healthy and traffic should be
   * reduced.
   * </pre>
   *
   * <code>float weight = 3;</code>
   * @return The weight.
   */
  @java.lang.Override
  public float getWeight() {
    return weight_;
  }

  public static final int AVAILABLE_RIF_FIELD_NUMBER = 4;
  private int availableRif_ = 0;
  /**
   * <pre>
   * Estimate of how many more in-flight requests the peer can handle.
   * </pre>
   *
   * <code>int32 available_rif = 4;</code>
   * @return The availableRif.
   */
  @java.lang.Override
  public int getAvailableRif() {
    return availableRif_;
  }

  public static final int CONVERGENCE_TIME_MS_FIELD_NUMBER = 5;
  private int convergenceTimeMs_ = 0;
  /**
   * <pre>
   * Clients should slowly move traffic over this period of time to avoid
   * sudden changes in traffic.
   * </pre>
   *
   * <code>int32 convergence_time_ms = 5;</code>
   * @return The convergenceTimeMs.
   */
  @java.lang.Override
  public int getConvergenceTimeMs() {
    return convergenceTimeMs_;
  }

  public static final int UTILIZATION_FIELD_NUMBER = 6;
  private float utilization_ = 0F;
  /**
   * <pre>
   * Note: these fields are implementation details that may not be set in the
   * future.
   * </pre>
   *
   * <code>float utilization = 6;</code>
   * @return The utilization.
   */
  @java.lang.Override
  public float getUtilization() {
    return utilization_;
  }

  public static final int CURRENT_RIF_FIELD_NUMBER = 7;
  private int currentRif_ = 0;
  /**
   * <code>int32 current_rif = 7;</code>
   * @return The currentRif.
   */
  @java.lang.Override
  public int getCurrentRif() {
    return currentRif_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (java.lang.Float.floatToRawIntBits(expectedLatencyMs_) != 0) {
      output.writeFloat(2, expectedLatencyMs_);
    }
    if (java.lang.Float.floatToRawIntBits(weight_) != 0) {
      output.writeFloat(3, weight_);
    }
    if (availableRif_ != 0) {
      output.writeInt32(4, availableRif_);
    }
    if (convergenceTimeMs_ != 0) {
      output.writeInt32(5, convergenceTimeMs_);
    }
    if (java.lang.Float.floatToRawIntBits(utilization_) != 0) {
      output.writeFloat(6, utilization_);
    }
    if (currentRif_ != 0) {
      output.writeInt32(7, currentRif_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (java.lang.Float.floatToRawIntBits(expectedLatencyMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, expectedLatencyMs_);
    }
    if (java.lang.Float.floatToRawIntBits(weight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, weight_);
    }
    if (availableRif_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, availableRif_);
    }
    if (convergenceTimeMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, convergenceTimeMs_);
    }
    if (java.lang.Float.floatToRawIntBits(utilization_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, utilization_);
    }
    if (currentRif_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, currentRif_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.bigtable.v2.PeerLoadInfo)) {
      return super.equals(obj);
    }
    com.google.bigtable.v2.PeerLoadInfo other = (com.google.bigtable.v2.PeerLoadInfo) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (java.lang.Float.floatToIntBits(getExpectedLatencyMs())
        != java.lang.Float.floatToIntBits(
            other.getExpectedLatencyMs())) return false;
    if (java.lang.Float.floatToIntBits(getWeight())
        != java.lang.Float.floatToIntBits(
            other.getWeight())) return false;
    if (getAvailableRif()
        != other.getAvailableRif()) return false;
    if (getConvergenceTimeMs()
        != other.getConvergenceTimeMs()) return false;
    if (java.lang.Float.floatToIntBits(getUtilization())
        != java.lang.Float.floatToIntBits(
            other.getUtilization())) return false;
    if (getCurrentRif()
        != other.getCurrentRif()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + EXPECTED_LATENCY_MS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getExpectedLatencyMs());
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getWeight());
    hash = (37 * hash) + AVAILABLE_RIF_FIELD_NUMBER;
    hash = (53 * hash) + getAvailableRif();
    hash = (37 * hash) + CONVERGENCE_TIME_MS_FIELD_NUMBER;
    hash = (53 * hash) + getConvergenceTimeMs();
    hash = (37 * hash) + UTILIZATION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getUtilization());
    hash = (37 * hash) + CURRENT_RIF_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentRif();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.bigtable.v2.PeerLoadInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.bigtable.v2.PeerLoadInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.bigtable.v2.PeerLoadInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PeerLoadInfo contains information about the peer that can be used for
   * load balancing.
   * (-- Next ID: 8 --)
   * </pre>
   *
   * Protobuf type {@code google.bigtable.v2.PeerLoadInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.bigtable.v2.PeerLoadInfo)
      com.google.bigtable.v2.PeerLoadInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.bigtable.v2.PeerInfoProto.internal_static_google_bigtable_v2_PeerLoadInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.bigtable.v2.PeerInfoProto.internal_static_google_bigtable_v2_PeerLoadInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.bigtable.v2.PeerLoadInfo.class, com.google.bigtable.v2.PeerLoadInfo.Builder.class);
    }

    // Construct using com.google.bigtable.v2.PeerLoadInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      version_ = 0;
      expectedLatencyMs_ = 0F;
      weight_ = 0F;
      availableRif_ = 0;
      convergenceTimeMs_ = 0;
      utilization_ = 0F;
      currentRif_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.bigtable.v2.PeerInfoProto.internal_static_google_bigtable_v2_PeerLoadInfo_descriptor;
    }

    @java.lang.Override
    public com.google.bigtable.v2.PeerLoadInfo getDefaultInstanceForType() {
      return com.google.bigtable.v2.PeerLoadInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.bigtable.v2.PeerLoadInfo build() {
      com.google.bigtable.v2.PeerLoadInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.bigtable.v2.PeerLoadInfo buildPartial() {
      com.google.bigtable.v2.PeerLoadInfo result = new com.google.bigtable.v2.PeerLoadInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.bigtable.v2.PeerLoadInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.expectedLatencyMs_ = expectedLatencyMs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.weight_ = weight_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.availableRif_ = availableRif_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.convergenceTimeMs_ = convergenceTimeMs_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.utilization_ = utilization_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.currentRif_ = currentRif_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.bigtable.v2.PeerLoadInfo) {
        return mergeFrom((com.google.bigtable.v2.PeerLoadInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.bigtable.v2.PeerLoadInfo other) {
      if (other == com.google.bigtable.v2.PeerLoadInfo.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getExpectedLatencyMs() != 0F) {
        setExpectedLatencyMs(other.getExpectedLatencyMs());
      }
      if (other.getWeight() != 0F) {
        setWeight(other.getWeight());
      }
      if (other.getAvailableRif() != 0) {
        setAvailableRif(other.getAvailableRif());
      }
      if (other.getConvergenceTimeMs() != 0) {
        setConvergenceTimeMs(other.getConvergenceTimeMs());
      }
      if (other.getUtilization() != 0F) {
        setUtilization(other.getUtilization());
      }
      if (other.getCurrentRif() != 0) {
        setCurrentRif(other.getCurrentRif());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              version_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              expectedLatencyMs_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              weight_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 32: {
              availableRif_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              convergenceTimeMs_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 53: {
              utilization_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 53
            case 56: {
              currentRif_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <pre>
     * PeerLoadInfo messages with different versions cannot be safely compared.
     * For example, one version of the logic may result in a lower expected,
     * latency, but that doesn't mean that the client should only send traffic to
     * the "faster" peers that use that version.
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <pre>
     * PeerLoadInfo messages with different versions cannot be safely compared.
     * For example, one version of the logic may result in a lower expected,
     * latency, but that doesn't mean that the client should only send traffic to
     * the "faster" peers that use that version.
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PeerLoadInfo messages with different versions cannot be safely compared.
     * For example, one version of the logic may result in a lower expected,
     * latency, but that doesn't mean that the client should only send traffic to
     * the "faster" peers that use that version.
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
      onChanged();
      return this;
    }

    private float expectedLatencyMs_ ;
    /**
     * <pre>
     * Peer's best guess as to how long requests will take. This may be noisy.
     * This does not include network latency.
     * </pre>
     *
     * <code>float expected_latency_ms = 2;</code>
     * @return The expectedLatencyMs.
     */
    @java.lang.Override
    public float getExpectedLatencyMs() {
      return expectedLatencyMs_;
    }
    /**
     * <pre>
     * Peer's best guess as to how long requests will take. This may be noisy.
     * This does not include network latency.
     * </pre>
     *
     * <code>float expected_latency_ms = 2;</code>
     * @param value The expectedLatencyMs to set.
     * @return This builder for chaining.
     */
    public Builder setExpectedLatencyMs(float value) {
      
      expectedLatencyMs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Peer's best guess as to how long requests will take. This may be noisy.
     * This does not include network latency.
     * </pre>
     *
     * <code>float expected_latency_ms = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpectedLatencyMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      expectedLatencyMs_ = 0F;
      onChanged();
      return this;
    }

    private float weight_ ;
    /**
     * <pre>
     * Higher weight means that the peer is less healthy and traffic should be
     * reduced.
     * </pre>
     *
     * <code>float weight = 3;</code>
     * @return The weight.
     */
    @java.lang.Override
    public float getWeight() {
      return weight_;
    }
    /**
     * <pre>
     * Higher weight means that the peer is less healthy and traffic should be
     * reduced.
     * </pre>
     *
     * <code>float weight = 3;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(float value) {
      
      weight_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Higher weight means that the peer is less healthy and traffic should be
     * reduced.
     * </pre>
     *
     * <code>float weight = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      bitField0_ = (bitField0_ & ~0x00000004);
      weight_ = 0F;
      onChanged();
      return this;
    }

    private int availableRif_ ;
    /**
     * <pre>
     * Estimate of how many more in-flight requests the peer can handle.
     * </pre>
     *
     * <code>int32 available_rif = 4;</code>
     * @return The availableRif.
     */
    @java.lang.Override
    public int getAvailableRif() {
      return availableRif_;
    }
    /**
     * <pre>
     * Estimate of how many more in-flight requests the peer can handle.
     * </pre>
     *
     * <code>int32 available_rif = 4;</code>
     * @param value The availableRif to set.
     * @return This builder for chaining.
     */
    public Builder setAvailableRif(int value) {
      
      availableRif_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Estimate of how many more in-flight requests the peer can handle.
     * </pre>
     *
     * <code>int32 available_rif = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailableRif() {
      bitField0_ = (bitField0_ & ~0x00000008);
      availableRif_ = 0;
      onChanged();
      return this;
    }

    private int convergenceTimeMs_ ;
    /**
     * <pre>
     * Clients should slowly move traffic over this period of time to avoid
     * sudden changes in traffic.
     * </pre>
     *
     * <code>int32 convergence_time_ms = 5;</code>
     * @return The convergenceTimeMs.
     */
    @java.lang.Override
    public int getConvergenceTimeMs() {
      return convergenceTimeMs_;
    }
    /**
     * <pre>
     * Clients should slowly move traffic over this period of time to avoid
     * sudden changes in traffic.
     * </pre>
     *
     * <code>int32 convergence_time_ms = 5;</code>
     * @param value The convergenceTimeMs to set.
     * @return This builder for chaining.
     */
    public Builder setConvergenceTimeMs(int value) {
      
      convergenceTimeMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Clients should slowly move traffic over this period of time to avoid
     * sudden changes in traffic.
     * </pre>
     *
     * <code>int32 convergence_time_ms = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearConvergenceTimeMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      convergenceTimeMs_ = 0;
      onChanged();
      return this;
    }

    private float utilization_ ;
    /**
     * <pre>
     * Note: these fields are implementation details that may not be set in the
     * future.
     * </pre>
     *
     * <code>float utilization = 6;</code>
     * @return The utilization.
     */
    @java.lang.Override
    public float getUtilization() {
      return utilization_;
    }
    /**
     * <pre>
     * Note: these fields are implementation details that may not be set in the
     * future.
     * </pre>
     *
     * <code>float utilization = 6;</code>
     * @param value The utilization to set.
     * @return This builder for chaining.
     */
    public Builder setUtilization(float value) {
      
      utilization_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Note: these fields are implementation details that may not be set in the
     * future.
     * </pre>
     *
     * <code>float utilization = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtilization() {
      bitField0_ = (bitField0_ & ~0x00000020);
      utilization_ = 0F;
      onChanged();
      return this;
    }

    private int currentRif_ ;
    /**
     * <code>int32 current_rif = 7;</code>
     * @return The currentRif.
     */
    @java.lang.Override
    public int getCurrentRif() {
      return currentRif_;
    }
    /**
     * <code>int32 current_rif = 7;</code>
     * @param value The currentRif to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentRif(int value) {
      
      currentRif_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 current_rif = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentRif() {
      bitField0_ = (bitField0_ & ~0x00000040);
      currentRif_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.bigtable.v2.PeerLoadInfo)
  }

  // @@protoc_insertion_point(class_scope:google.bigtable.v2.PeerLoadInfo)
  private static final com.google.bigtable.v2.PeerLoadInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.bigtable.v2.PeerLoadInfo();
  }

  public static com.google.bigtable.v2.PeerLoadInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PeerLoadInfo>
      PARSER = new com.google.protobuf.AbstractParser<PeerLoadInfo>() {
    @java.lang.Override
    public PeerLoadInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PeerLoadInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PeerLoadInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.bigtable.v2.PeerLoadInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

