// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/peer_info.proto

package com.google.bigtable.v2;

public final class PeerInfoProto {
  private PeerInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_PeerLoadInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_PeerLoadInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_PeerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_PeerInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"google/bigtable/v2/peer_info.proto\022\022go" +
      "ogle.bigtable.v2\"\252\001\n\014PeerLoadInfo\022\017\n\007ver" +
      "sion\030\001 \001(\005\022\033\n\023expected_latency_ms\030\002 \001(\002\022" +
      "\016\n\006weight\030\003 \001(\002\022\025\n\ravailable_rif\030\004 \001(\005\022\033" +
      "\n\023convergence_time_ms\030\005 \001(\005\022\023\n\013utilizati" +
      "on\030\006 \001(\002\022\023\n\013current_rif\030\007 \001(\005\"\330\004\n\010PeerIn" +
      "fo\022\032\n\022google_frontend_id\030\001 \001(\003\022\037\n\027applic" +
      "ation_frontend_id\030\002 \001(\003\022#\n\033application_f" +
      "rontend_region\030\006 \001(\t\022%\n\031application_fron" +
      "tend_zone\030\003 \001(\tB\002\030\001\022$\n\034application_front" +
      "end_subzone\030\004 \001(\t\022B\n\016transport_type\030\005 \001(" +
      "\0162*.google.bigtable.v2.PeerInfo.Transpor" +
      "tType\0223\n\tload_info\030\007 \001(\0132 .google.bigtab" +
      "le.v2.PeerLoadInfo\"\243\002\n\rTransportType\022\032\n\026" +
      "TRANSPORT_TYPE_UNKNOWN\020\000\022\033\n\027TRANSPORT_TY" +
      "PE_EXTERNAL\020\001\022\035\n\031TRANSPORT_TYPE_CLOUD_PA" +
      "TH\020\002\022 \n\034TRANSPORT_TYPE_DIRECT_ACCESS\020\003\022\"" +
      "\n\036TRANSPORT_TYPE_SESSION_UNKNOWN\020\004\022#\n\037TR" +
      "ANSPORT_TYPE_SESSION_EXTERNAL\020\005\022%\n!TRANS" +
      "PORT_TYPE_SESSION_CLOUD_PATH\020\006\022(\n$TRANSP" +
      "ORT_TYPE_SESSION_DIRECT_ACCESS\020\007B\267\001\n\026com" +
      ".google.bigtable.v2B\rPeerInfoProtoP\001Z8cl" +
      "oud.google.com/go/bigtable/apiv2/bigtabl" +
      "epb;bigtablepb\252\002\030Google.Cloud.Bigtable.V" +
      "2\312\002\030Google\\Cloud\\Bigtable\\V2\352\002\033Google::C" +
      "loud::Bigtable::V2b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_bigtable_v2_PeerLoadInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_bigtable_v2_PeerLoadInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_PeerLoadInfo_descriptor,
        new java.lang.String[] { "Version", "ExpectedLatencyMs", "Weight", "AvailableRif", "ConvergenceTimeMs", "Utilization", "CurrentRif", });
    internal_static_google_bigtable_v2_PeerInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_bigtable_v2_PeerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_PeerInfo_descriptor,
        new java.lang.String[] { "GoogleFrontendId", "ApplicationFrontendId", "ApplicationFrontendRegion", "ApplicationFrontendZone", "ApplicationFrontendSubzone", "TransportType", "LoadInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
