// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/peer_info.proto

package com.google.bigtable.v2;

public interface PeerLoadInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.PeerLoadInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * PeerLoadInfo messages with different versions cannot be safely compared.
   * For example, one version of the logic may result in a lower expected,
   * latency, but that doesn't mean that the client should only send traffic to
   * the "faster" peers that use that version.
   * </pre>
   *
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   * Peer's best guess as to how long requests will take. This may be noisy.
   * This does not include network latency.
   * </pre>
   *
   * <code>float expected_latency_ms = 2;</code>
   * @return The expectedLatencyMs.
   */
  float getExpectedLatencyMs();

  /**
   * <pre>
   * Higher weight means that the peer is less healthy and traffic should be
   * reduced.
   * </pre>
   *
   * <code>float weight = 3;</code>
   * @return The weight.
   */
  float getWeight();

  /**
   * <pre>
   * Estimate of how many more in-flight requests the peer can handle.
   * </pre>
   *
   * <code>int32 available_rif = 4;</code>
   * @return The availableRif.
   */
  int getAvailableRif();

  /**
   * <pre>
   * Clients should slowly move traffic over this period of time to avoid
   * sudden changes in traffic.
   * </pre>
   *
   * <code>int32 convergence_time_ms = 5;</code>
   * @return The convergenceTimeMs.
   */
  int getConvergenceTimeMs();

  /**
   * <pre>
   * Note: these fields are implementation details that may not be set in the
   * future.
   * </pre>
   *
   * <code>float utilization = 6;</code>
   * @return The utilization.
   */
  float getUtilization();

  /**
   * <code>int32 current_rif = 7;</code>
   * @return The currentRif.
   */
  int getCurrentRif();
}
