// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/session.proto

package com.google.bigtable.v2;

/**
 * Protobuf type {@code google.bigtable.v2.PeerLoadUpdateResponse}
 */
public final class PeerLoadUpdateResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.bigtable.v2.PeerLoadUpdateResponse)
    PeerLoadUpdateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PeerLoadUpdateResponse.newBuilder() to construct.
  private PeerLoadUpdateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PeerLoadUpdateResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PeerLoadUpdateResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.bigtable.v2.SessionProto.internal_static_google_bigtable_v2_PeerLoadUpdateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.bigtable.v2.SessionProto.internal_static_google_bigtable_v2_PeerLoadUpdateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.bigtable.v2.PeerLoadUpdateResponse.class, com.google.bigtable.v2.PeerLoadUpdateResponse.Builder.class);
  }

  public static final int LOAD_INFO_FIELD_NUMBER = 1;
  private com.google.bigtable.v2.PeerLoadInfo loadInfo_;
  /**
   * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
   * @return Whether the loadInfo field is set.
   */
  @java.lang.Override
  public boolean hasLoadInfo() {
    return loadInfo_ != null;
  }
  /**
   * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
   * @return The loadInfo.
   */
  @java.lang.Override
  public com.google.bigtable.v2.PeerLoadInfo getLoadInfo() {
    return loadInfo_ == null ? com.google.bigtable.v2.PeerLoadInfo.getDefaultInstance() : loadInfo_;
  }
  /**
   * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
   */
  @java.lang.Override
  public com.google.bigtable.v2.PeerLoadInfoOrBuilder getLoadInfoOrBuilder() {
    return loadInfo_ == null ? com.google.bigtable.v2.PeerLoadInfo.getDefaultInstance() : loadInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (loadInfo_ != null) {
      output.writeMessage(1, getLoadInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (loadInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLoadInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.bigtable.v2.PeerLoadUpdateResponse)) {
      return super.equals(obj);
    }
    com.google.bigtable.v2.PeerLoadUpdateResponse other = (com.google.bigtable.v2.PeerLoadUpdateResponse) obj;

    if (hasLoadInfo() != other.hasLoadInfo()) return false;
    if (hasLoadInfo()) {
      if (!getLoadInfo()
          .equals(other.getLoadInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLoadInfo()) {
      hash = (37 * hash) + LOAD_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getLoadInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.bigtable.v2.PeerLoadUpdateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.bigtable.v2.PeerLoadUpdateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.bigtable.v2.PeerLoadUpdateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.bigtable.v2.PeerLoadUpdateResponse)
      com.google.bigtable.v2.PeerLoadUpdateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.bigtable.v2.SessionProto.internal_static_google_bigtable_v2_PeerLoadUpdateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.bigtable.v2.SessionProto.internal_static_google_bigtable_v2_PeerLoadUpdateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.bigtable.v2.PeerLoadUpdateResponse.class, com.google.bigtable.v2.PeerLoadUpdateResponse.Builder.class);
    }

    // Construct using com.google.bigtable.v2.PeerLoadUpdateResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      loadInfo_ = null;
      if (loadInfoBuilder_ != null) {
        loadInfoBuilder_.dispose();
        loadInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.bigtable.v2.SessionProto.internal_static_google_bigtable_v2_PeerLoadUpdateResponse_descriptor;
    }

    @java.lang.Override
    public com.google.bigtable.v2.PeerLoadUpdateResponse getDefaultInstanceForType() {
      return com.google.bigtable.v2.PeerLoadUpdateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.bigtable.v2.PeerLoadUpdateResponse build() {
      com.google.bigtable.v2.PeerLoadUpdateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.bigtable.v2.PeerLoadUpdateResponse buildPartial() {
      com.google.bigtable.v2.PeerLoadUpdateResponse result = new com.google.bigtable.v2.PeerLoadUpdateResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.bigtable.v2.PeerLoadUpdateResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.loadInfo_ = loadInfoBuilder_ == null
            ? loadInfo_
            : loadInfoBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.bigtable.v2.PeerLoadUpdateResponse) {
        return mergeFrom((com.google.bigtable.v2.PeerLoadUpdateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.bigtable.v2.PeerLoadUpdateResponse other) {
      if (other == com.google.bigtable.v2.PeerLoadUpdateResponse.getDefaultInstance()) return this;
      if (other.hasLoadInfo()) {
        mergeLoadInfo(other.getLoadInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getLoadInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.bigtable.v2.PeerLoadInfo loadInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.bigtable.v2.PeerLoadInfo, com.google.bigtable.v2.PeerLoadInfo.Builder, com.google.bigtable.v2.PeerLoadInfoOrBuilder> loadInfoBuilder_;
    /**
     * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
     * @return Whether the loadInfo field is set.
     */
    public boolean hasLoadInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
     * @return The loadInfo.
     */
    public com.google.bigtable.v2.PeerLoadInfo getLoadInfo() {
      if (loadInfoBuilder_ == null) {
        return loadInfo_ == null ? com.google.bigtable.v2.PeerLoadInfo.getDefaultInstance() : loadInfo_;
      } else {
        return loadInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
     */
    public Builder setLoadInfo(com.google.bigtable.v2.PeerLoadInfo value) {
      if (loadInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        loadInfo_ = value;
      } else {
        loadInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
     */
    public Builder setLoadInfo(
        com.google.bigtable.v2.PeerLoadInfo.Builder builderForValue) {
      if (loadInfoBuilder_ == null) {
        loadInfo_ = builderForValue.build();
      } else {
        loadInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
     */
    public Builder mergeLoadInfo(com.google.bigtable.v2.PeerLoadInfo value) {
      if (loadInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          loadInfo_ != null &&
          loadInfo_ != com.google.bigtable.v2.PeerLoadInfo.getDefaultInstance()) {
          getLoadInfoBuilder().mergeFrom(value);
        } else {
          loadInfo_ = value;
        }
      } else {
        loadInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
     */
    public Builder clearLoadInfo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      loadInfo_ = null;
      if (loadInfoBuilder_ != null) {
        loadInfoBuilder_.dispose();
        loadInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
     */
    public com.google.bigtable.v2.PeerLoadInfo.Builder getLoadInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getLoadInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
     */
    public com.google.bigtable.v2.PeerLoadInfoOrBuilder getLoadInfoOrBuilder() {
      if (loadInfoBuilder_ != null) {
        return loadInfoBuilder_.getMessageOrBuilder();
      } else {
        return loadInfo_ == null ?
            com.google.bigtable.v2.PeerLoadInfo.getDefaultInstance() : loadInfo_;
      }
    }
    /**
     * <code>.google.bigtable.v2.PeerLoadInfo load_info = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.bigtable.v2.PeerLoadInfo, com.google.bigtable.v2.PeerLoadInfo.Builder, com.google.bigtable.v2.PeerLoadInfoOrBuilder> 
        getLoadInfoFieldBuilder() {
      if (loadInfoBuilder_ == null) {
        loadInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.bigtable.v2.PeerLoadInfo, com.google.bigtable.v2.PeerLoadInfo.Builder, com.google.bigtable.v2.PeerLoadInfoOrBuilder>(
                getLoadInfo(),
                getParentForChildren(),
                isClean());
        loadInfo_ = null;
      }
      return loadInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.bigtable.v2.PeerLoadUpdateResponse)
  }

  // @@protoc_insertion_point(class_scope:google.bigtable.v2.PeerLoadUpdateResponse)
  private static final com.google.bigtable.v2.PeerLoadUpdateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.bigtable.v2.PeerLoadUpdateResponse();
  }

  public static com.google.bigtable.v2.PeerLoadUpdateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PeerLoadUpdateResponse>
      PARSER = new com.google.protobuf.AbstractParser<PeerLoadUpdateResponse>() {
    @java.lang.Override
    public PeerLoadUpdateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PeerLoadUpdateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PeerLoadUpdateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.bigtable.v2.PeerLoadUpdateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

