// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/request_stats.proto
// Protobuf Java Version: 4.33.6

package com.google.bigtable.v2;

/**
 * <pre>
 * ReadIterationStats captures information about the iteration of rows or cells
 * over the course of a read, e.g. how many results were scanned in a read
 * operation versus the results returned.
 * </pre>
 *
 * Protobuf type {@code google.bigtable.v2.ReadIterationStats}
 */
@com.google.protobuf.Generated
public final class ReadIterationStats extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.bigtable.v2.ReadIterationStats)
    ReadIterationStatsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 6,
      /* suffix= */ "",
      "ReadIterationStats");
  }
  // Use ReadIterationStats.newBuilder() to construct.
  private ReadIterationStats(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ReadIterationStats() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.bigtable.v2.ReadIterationStats.class, com.google.bigtable.v2.ReadIterationStats.Builder.class);
  }

  public interface MemoryLayerStatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.bigtable.v2.ReadIterationStats.MemoryLayerStats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Reason why the entire request cannot use the memory layer.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason request_ineligibility_reason = 1;</code>
     * @return The enum numeric value on the wire for requestIneligibilityReason.
     */
    int getRequestIneligibilityReasonValue();
    /**
     * <pre>
     * Reason why the entire request cannot use the memory layer.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason request_ineligibility_reason = 1;</code>
     * @return The requestIneligibilityReason.
     */
    com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason getRequestIneligibilityReason();

    /**
     * <pre>
     * Number of times a row access attempt resulted in a given outcome.
     * Only contains the very first result for each row.
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
     */
    int getRowResultCountsCount();
    /**
     * <pre>
     * Number of times a row access attempt resulted in a given outcome.
     * Only contains the very first result for each row.
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
     */
    boolean containsRowResultCounts(
        int key);
    /**
     * Use {@link #getRowResultCountsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Long>
    getRowResultCounts();
    /**
     * <pre>
     * Number of times a row access attempt resulted in a given outcome.
     * Only contains the very first result for each row.
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Long>
    getRowResultCountsMap();
    /**
     * <pre>
     * Number of times a row access attempt resulted in a given outcome.
     * Only contains the very first result for each row.
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
     */
    long getRowResultCountsOrDefault(
        int key,
        long defaultValue);
    /**
     * <pre>
     * Number of times a row access attempt resulted in a given outcome.
     * Only contains the very first result for each row.
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
     */
    long getRowResultCountsOrThrow(
        int key);
  }
  /**
   * <pre>
   * Captures information about the usage of the memory layer during the read.
   * </pre>
   *
   * Protobuf type {@code google.bigtable.v2.ReadIterationStats.MemoryLayerStats}
   */
  public static final class MemoryLayerStats extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:google.bigtable.v2.ReadIterationStats.MemoryLayerStats)
      MemoryLayerStatsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 6,
        /* suffix= */ "",
        "MemoryLayerStats");
    }
    // Use MemoryLayerStats.newBuilder() to construct.
    private MemoryLayerStats(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MemoryLayerStats() {
      requestIneligibilityReason_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_MemoryLayerStats_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetRowResultCounts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_MemoryLayerStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.class, com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.Builder.class);
    }

    /**
     * <pre>
     * Reason why the entire request cannot use the memory layer.
     * </pre>
     *
     * Protobuf enum {@code google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason}
     */
    public enum RequestIneligibilityReason
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * The request was eligible to use the memory layer.
       * </pre>
       *
       * <code>REQUEST_ELIGIBLE = 0;</code>
       */
      REQUEST_ELIGIBLE(0),
      /**
       * <pre>
       * The client library version is outdated and does not support the memory
       * layer.
       * </pre>
       *
       * <code>CLIENT_VERSION_OUTDATED = 1;</code>
       */
      CLIENT_VERSION_OUTDATED(1),
      /**
       * <pre>
       * The app profile used for the request does not have a memory layer
       * configured.
       * </pre>
       *
       * <code>APP_PROFILE_NO_MEMORY_CONFIG = 2;</code>
       */
      APP_PROFILE_NO_MEMORY_CONFIG(2),
      /**
       * <pre>
       * The request was throttled and bypassed the memory layer.
       * </pre>
       *
       * <code>REQUEST_THROTTLED = 3;</code>
       */
      REQUEST_THROTTLED(3),
      /**
       * <pre>
       * The rowset in the request is not supported by the memory layer.
       * </pre>
       *
       * <code>ROWSET_INELIGIBLE = 4;</code>
       */
      ROWSET_INELIGIBLE(4),
      /**
       * <pre>
       * The filter in the request is not supported by the memory layer.
       * </pre>
       *
       * <code>FILTER_INELIGIBLE = 5;</code>
       */
      FILTER_INELIGIBLE(5),
      /**
       * <pre>
       * The memory layer is disabled or unavailable.
       * </pre>
       *
       * <code>MEMORY_LAYER_DISABLED = 6;</code>
       */
      MEMORY_LAYER_DISABLED(6),
      /**
       * <pre>
       * The request was executed with a transaction, which is not supported by
       * the memory layer.
       * </pre>
       *
       * <code>TRANSACTIONS_UNSUPPORTED = 7;</code>
       */
      TRANSACTIONS_UNSUPPORTED(7),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 33,
          /* patch= */ 6,
          /* suffix= */ "",
          "RequestIneligibilityReason");
      }
      /**
       * <pre>
       * The request was eligible to use the memory layer.
       * </pre>
       *
       * <code>REQUEST_ELIGIBLE = 0;</code>
       */
      public static final int REQUEST_ELIGIBLE_VALUE = 0;
      /**
       * <pre>
       * The client library version is outdated and does not support the memory
       * layer.
       * </pre>
       *
       * <code>CLIENT_VERSION_OUTDATED = 1;</code>
       */
      public static final int CLIENT_VERSION_OUTDATED_VALUE = 1;
      /**
       * <pre>
       * The app profile used for the request does not have a memory layer
       * configured.
       * </pre>
       *
       * <code>APP_PROFILE_NO_MEMORY_CONFIG = 2;</code>
       */
      public static final int APP_PROFILE_NO_MEMORY_CONFIG_VALUE = 2;
      /**
       * <pre>
       * The request was throttled and bypassed the memory layer.
       * </pre>
       *
       * <code>REQUEST_THROTTLED = 3;</code>
       */
      public static final int REQUEST_THROTTLED_VALUE = 3;
      /**
       * <pre>
       * The rowset in the request is not supported by the memory layer.
       * </pre>
       *
       * <code>ROWSET_INELIGIBLE = 4;</code>
       */
      public static final int ROWSET_INELIGIBLE_VALUE = 4;
      /**
       * <pre>
       * The filter in the request is not supported by the memory layer.
       * </pre>
       *
       * <code>FILTER_INELIGIBLE = 5;</code>
       */
      public static final int FILTER_INELIGIBLE_VALUE = 5;
      /**
       * <pre>
       * The memory layer is disabled or unavailable.
       * </pre>
       *
       * <code>MEMORY_LAYER_DISABLED = 6;</code>
       */
      public static final int MEMORY_LAYER_DISABLED_VALUE = 6;
      /**
       * <pre>
       * The request was executed with a transaction, which is not supported by
       * the memory layer.
       * </pre>
       *
       * <code>TRANSACTIONS_UNSUPPORTED = 7;</code>
       */
      public static final int TRANSACTIONS_UNSUPPORTED_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestIneligibilityReason valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static RequestIneligibilityReason forNumber(int value) {
        switch (value) {
          case 0: return REQUEST_ELIGIBLE;
          case 1: return CLIENT_VERSION_OUTDATED;
          case 2: return APP_PROFILE_NO_MEMORY_CONFIG;
          case 3: return REQUEST_THROTTLED;
          case 4: return ROWSET_INELIGIBLE;
          case 5: return FILTER_INELIGIBLE;
          case 6: return MEMORY_LAYER_DISABLED;
          case 7: return TRANSACTIONS_UNSUPPORTED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestIneligibilityReason>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RequestIneligibilityReason> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestIneligibilityReason>() {
              public RequestIneligibilityReason findValueByNumber(int number) {
                return RequestIneligibilityReason.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestIneligibilityReason[] VALUES = values();

      public static RequestIneligibilityReason valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RequestIneligibilityReason(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason)
    }

    public static final int REQUEST_INELIGIBILITY_REASON_FIELD_NUMBER = 1;
    private int requestIneligibilityReason_ = 0;
    /**
     * <pre>
     * Reason why the entire request cannot use the memory layer.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason request_ineligibility_reason = 1;</code>
     * @return The enum numeric value on the wire for requestIneligibilityReason.
     */
    @java.lang.Override public int getRequestIneligibilityReasonValue() {
      return requestIneligibilityReason_;
    }
    /**
     * <pre>
     * Reason why the entire request cannot use the memory layer.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason request_ineligibility_reason = 1;</code>
     * @return The requestIneligibilityReason.
     */
    @java.lang.Override public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason getRequestIneligibilityReason() {
      com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason result = com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason.forNumber(requestIneligibilityReason_);
      return result == null ? com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason.UNRECOGNIZED : result;
    }

    public static final int ROW_RESULT_COUNTS_FIELD_NUMBER = 2;
    private static final class RowResultCountsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Long>newDefaultInstance(
                  com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_MemoryLayerStats_RowResultCountsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Long> rowResultCounts_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
    internalGetRowResultCounts() {
      if (rowResultCounts_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RowResultCountsDefaultEntryHolder.defaultEntry);
      }
      return rowResultCounts_;
    }
    public int getRowResultCountsCount() {
      return internalGetRowResultCounts().getMap().size();
    }
    /**
     * <pre>
     * Number of times a row access attempt resulted in a given outcome.
     * Only contains the very first result for each row.
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
     */
    @java.lang.Override
    public boolean containsRowResultCounts(
        int key) {

      return internalGetRowResultCounts().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRowResultCountsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Long> getRowResultCounts() {
      return getRowResultCountsMap();
    }
    /**
     * <pre>
     * Number of times a row access attempt resulted in a given outcome.
     * Only contains the very first result for each row.
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, java.lang.Long> getRowResultCountsMap() {
      return internalGetRowResultCounts().getMap();
    }
    /**
     * <pre>
     * Number of times a row access attempt resulted in a given outcome.
     * Only contains the very first result for each row.
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
     */
    @java.lang.Override
    public long getRowResultCountsOrDefault(
        int key,
        long defaultValue) {

      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetRowResultCounts().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Number of times a row access attempt resulted in a given outcome.
     * Only contains the very first result for each row.
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
     */
    @java.lang.Override
    public long getRowResultCountsOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetRowResultCounts().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestIneligibilityReason_ != com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason.REQUEST_ELIGIBLE.getNumber()) {
        output.writeEnum(1, requestIneligibilityReason_);
      }
      com.google.protobuf.GeneratedMessage
        .serializeIntegerMapTo(
          output,
          internalGetRowResultCounts(),
          RowResultCountsDefaultEntryHolder.defaultEntry,
          2);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestIneligibilityReason_ != com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason.REQUEST_ELIGIBLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, requestIneligibilityReason_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Long> entry
           : internalGetRowResultCounts().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
        rowResultCounts__ = RowResultCountsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, rowResultCounts__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats)) {
        return super.equals(obj);
      }
      com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats other = (com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats) obj;

      if (requestIneligibilityReason_ != other.requestIneligibilityReason_) return false;
      if (!internalGetRowResultCounts().equals(
          other.internalGetRowResultCounts())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_INELIGIBILITY_REASON_FIELD_NUMBER;
      hash = (53 * hash) + requestIneligibilityReason_;
      if (!internalGetRowResultCounts().getMap().isEmpty()) {
        hash = (37 * hash) + ROW_RESULT_COUNTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetRowResultCounts().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Captures information about the usage of the memory layer during the read.
     * </pre>
     *
     * Protobuf type {@code google.bigtable.v2.ReadIterationStats.MemoryLayerStats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.bigtable.v2.ReadIterationStats.MemoryLayerStats)
        com.google.bigtable.v2.ReadIterationStats.MemoryLayerStatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_MemoryLayerStats_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetRowResultCounts();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableRowResultCounts();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_MemoryLayerStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.class, com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.Builder.class);
      }

      // Construct using com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestIneligibilityReason_ = 0;
        internalGetMutableRowResultCounts().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_MemoryLayerStats_descriptor;
      }

      @java.lang.Override
      public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats getDefaultInstanceForType() {
        return com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats build() {
        com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats buildPartial() {
        com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats result = new com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestIneligibilityReason_ = requestIneligibilityReason_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.rowResultCounts_ = internalGetRowResultCounts();
          result.rowResultCounts_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats) {
          return mergeFrom((com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats other) {
        if (other == com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.getDefaultInstance()) return this;
        if (other.requestIneligibilityReason_ != 0) {
          setRequestIneligibilityReasonValue(other.getRequestIneligibilityReasonValue());
        }
        internalGetMutableRowResultCounts().mergeFrom(
            other.internalGetRowResultCounts());
        bitField0_ |= 0x00000002;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                requestIneligibilityReason_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
                rowResultCounts__ = input.readMessage(
                    RowResultCountsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableRowResultCounts().getMutableMap().put(
                    rowResultCounts__.getKey(), rowResultCounts__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int requestIneligibilityReason_ = 0;
      /**
       * <pre>
       * Reason why the entire request cannot use the memory layer.
       * </pre>
       *
       * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason request_ineligibility_reason = 1;</code>
       * @return The enum numeric value on the wire for requestIneligibilityReason.
       */
      @java.lang.Override public int getRequestIneligibilityReasonValue() {
        return requestIneligibilityReason_;
      }
      /**
       * <pre>
       * Reason why the entire request cannot use the memory layer.
       * </pre>
       *
       * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason request_ineligibility_reason = 1;</code>
       * @param value The enum numeric value on the wire for requestIneligibilityReason to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIneligibilityReasonValue(int value) {
        requestIneligibilityReason_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Reason why the entire request cannot use the memory layer.
       * </pre>
       *
       * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason request_ineligibility_reason = 1;</code>
       * @return The requestIneligibilityReason.
       */
      @java.lang.Override
      public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason getRequestIneligibilityReason() {
        com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason result = com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason.forNumber(requestIneligibilityReason_);
        return result == null ? com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Reason why the entire request cannot use the memory layer.
       * </pre>
       *
       * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason request_ineligibility_reason = 1;</code>
       * @param value The requestIneligibilityReason to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIneligibilityReason(com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000001;
        requestIneligibilityReason_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Reason why the entire request cannot use the memory layer.
       * </pre>
       *
       * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.RequestIneligibilityReason request_ineligibility_reason = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestIneligibilityReason() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestIneligibilityReason_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Long> rowResultCounts_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
          internalGetRowResultCounts() {
        if (rowResultCounts_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              RowResultCountsDefaultEntryHolder.defaultEntry);
        }
        return rowResultCounts_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
          internalGetMutableRowResultCounts() {
        if (rowResultCounts_ == null) {
          rowResultCounts_ = com.google.protobuf.MapField.newMapField(
              RowResultCountsDefaultEntryHolder.defaultEntry);
        }
        if (!rowResultCounts_.isMutable()) {
          rowResultCounts_ = rowResultCounts_.copy();
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return rowResultCounts_;
      }
      public int getRowResultCountsCount() {
        return internalGetRowResultCounts().getMap().size();
      }
      /**
       * <pre>
       * Number of times a row access attempt resulted in a given outcome.
       * Only contains the very first result for each row.
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
       */
      @java.lang.Override
      public boolean containsRowResultCounts(
          int key) {

        return internalGetRowResultCounts().getMap().containsKey(key);
      }
      /**
       * Use {@link #getRowResultCountsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Long> getRowResultCounts() {
        return getRowResultCountsMap();
      }
      /**
       * <pre>
       * Number of times a row access attempt resulted in a given outcome.
       * Only contains the very first result for each row.
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, java.lang.Long> getRowResultCountsMap() {
        return internalGetRowResultCounts().getMap();
      }
      /**
       * <pre>
       * Number of times a row access attempt resulted in a given outcome.
       * Only contains the very first result for each row.
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
       */
      @java.lang.Override
      public long getRowResultCountsOrDefault(
          int key,
          long defaultValue) {

        java.util.Map<java.lang.Integer, java.lang.Long> map =
            internalGetRowResultCounts().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Number of times a row access attempt resulted in a given outcome.
       * Only contains the very first result for each row.
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
       */
      @java.lang.Override
      public long getRowResultCountsOrThrow(
          int key) {

        java.util.Map<java.lang.Integer, java.lang.Long> map =
            internalGetRowResultCounts().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearRowResultCounts() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableRowResultCounts().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Number of times a row access attempt resulted in a given outcome.
       * Only contains the very first result for each row.
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
       */
      public Builder removeRowResultCounts(
          int key) {

        internalGetMutableRowResultCounts().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Long>
          getMutableRowResultCounts() {
        bitField0_ |= 0x00000002;
        return internalGetMutableRowResultCounts().getMutableMap();
      }
      /**
       * <pre>
       * Number of times a row access attempt resulted in a given outcome.
       * Only contains the very first result for each row.
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
       */
      public Builder putRowResultCounts(
          int key,
          long value) {


        internalGetMutableRowResultCounts().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * Number of times a row access attempt resulted in a given outcome.
       * Only contains the very first result for each row.
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; row_result_counts = 2;</code>
       */
      public Builder putAllRowResultCounts(
          java.util.Map<java.lang.Integer, java.lang.Long> values) {
        internalGetMutableRowResultCounts().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }

      // @@protoc_insertion_point(builder_scope:google.bigtable.v2.ReadIterationStats.MemoryLayerStats)
    }

    // @@protoc_insertion_point(class_scope:google.bigtable.v2.ReadIterationStats.MemoryLayerStats)
    private static final com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats();
    }

    public static com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MemoryLayerStats>
        PARSER = new com.google.protobuf.AbstractParser<MemoryLayerStats>() {
      @java.lang.Override
      public MemoryLayerStats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MemoryLayerStats> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MemoryLayerStats> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int ROWS_SEEN_COUNT_FIELD_NUMBER = 1;
  private long rowsSeenCount_ = 0L;
  /**
   * <pre>
   * The rows seen (scanned) as part of the request. This includes the count of
   * rows returned, as captured below.
   * </pre>
   *
   * <code>int64 rows_seen_count = 1;</code>
   * @return The rowsSeenCount.
   */
  @java.lang.Override
  public long getRowsSeenCount() {
    return rowsSeenCount_;
  }

  public static final int ROWS_RETURNED_COUNT_FIELD_NUMBER = 2;
  private long rowsReturnedCount_ = 0L;
  /**
   * <pre>
   * The rows returned as part of the request.
   * </pre>
   *
   * <code>int64 rows_returned_count = 2;</code>
   * @return The rowsReturnedCount.
   */
  @java.lang.Override
  public long getRowsReturnedCount() {
    return rowsReturnedCount_;
  }

  public static final int CELLS_SEEN_COUNT_FIELD_NUMBER = 3;
  private long cellsSeenCount_ = 0L;
  /**
   * <pre>
   * The cells seen (scanned) as part of the request. This includes the count of
   * cells returned, as captured below.
   * </pre>
   *
   * <code>int64 cells_seen_count = 3;</code>
   * @return The cellsSeenCount.
   */
  @java.lang.Override
  public long getCellsSeenCount() {
    return cellsSeenCount_;
  }

  public static final int CELLS_RETURNED_COUNT_FIELD_NUMBER = 4;
  private long cellsReturnedCount_ = 0L;
  /**
   * <pre>
   * The cells returned as part of the request.
   * </pre>
   *
   * <code>int64 cells_returned_count = 4;</code>
   * @return The cellsReturnedCount.
   */
  @java.lang.Override
  public long getCellsReturnedCount() {
    return cellsReturnedCount_;
  }

  public static final int MEMORY_LAYER_STATS_FIELD_NUMBER = 6;
  private com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memoryLayerStats_;
  /**
   * <pre>
   * Statistics about the memory layer for this read.
   * </pre>
   *
   * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
   * @return Whether the memoryLayerStats field is set.
   */
  @java.lang.Override
  public boolean hasMemoryLayerStats() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Statistics about the memory layer for this read.
   * </pre>
   *
   * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
   * @return The memoryLayerStats.
   */
  @java.lang.Override
  public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats getMemoryLayerStats() {
    return memoryLayerStats_ == null ? com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.getDefaultInstance() : memoryLayerStats_;
  }
  /**
   * <pre>
   * Statistics about the memory layer for this read.
   * </pre>
   *
   * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
   */
  @java.lang.Override
  public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStatsOrBuilder getMemoryLayerStatsOrBuilder() {
    return memoryLayerStats_ == null ? com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.getDefaultInstance() : memoryLayerStats_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rowsSeenCount_ != 0L) {
      output.writeInt64(1, rowsSeenCount_);
    }
    if (rowsReturnedCount_ != 0L) {
      output.writeInt64(2, rowsReturnedCount_);
    }
    if (cellsSeenCount_ != 0L) {
      output.writeInt64(3, cellsSeenCount_);
    }
    if (cellsReturnedCount_ != 0L) {
      output.writeInt64(4, cellsReturnedCount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getMemoryLayerStats());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rowsSeenCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, rowsSeenCount_);
    }
    if (rowsReturnedCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, rowsReturnedCount_);
    }
    if (cellsSeenCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, cellsSeenCount_);
    }
    if (cellsReturnedCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, cellsReturnedCount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getMemoryLayerStats());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.bigtable.v2.ReadIterationStats)) {
      return super.equals(obj);
    }
    com.google.bigtable.v2.ReadIterationStats other = (com.google.bigtable.v2.ReadIterationStats) obj;

    if (getRowsSeenCount()
        != other.getRowsSeenCount()) return false;
    if (getRowsReturnedCount()
        != other.getRowsReturnedCount()) return false;
    if (getCellsSeenCount()
        != other.getCellsSeenCount()) return false;
    if (getCellsReturnedCount()
        != other.getCellsReturnedCount()) return false;
    if (hasMemoryLayerStats() != other.hasMemoryLayerStats()) return false;
    if (hasMemoryLayerStats()) {
      if (!getMemoryLayerStats()
          .equals(other.getMemoryLayerStats())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROWS_SEEN_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRowsSeenCount());
    hash = (37 * hash) + ROWS_RETURNED_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRowsReturnedCount());
    hash = (37 * hash) + CELLS_SEEN_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCellsSeenCount());
    hash = (37 * hash) + CELLS_RETURNED_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCellsReturnedCount());
    if (hasMemoryLayerStats()) {
      hash = (37 * hash) + MEMORY_LAYER_STATS_FIELD_NUMBER;
      hash = (53 * hash) + getMemoryLayerStats().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.bigtable.v2.ReadIterationStats parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.ReadIterationStats parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.ReadIterationStats parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.ReadIterationStats parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.ReadIterationStats parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.ReadIterationStats parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.ReadIterationStats parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.bigtable.v2.ReadIterationStats parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.bigtable.v2.ReadIterationStats parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.bigtable.v2.ReadIterationStats parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.bigtable.v2.ReadIterationStats parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.bigtable.v2.ReadIterationStats parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.bigtable.v2.ReadIterationStats prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ReadIterationStats captures information about the iteration of rows or cells
   * over the course of a read, e.g. how many results were scanned in a read
   * operation versus the results returned.
   * </pre>
   *
   * Protobuf type {@code google.bigtable.v2.ReadIterationStats}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.bigtable.v2.ReadIterationStats)
      com.google.bigtable.v2.ReadIterationStatsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.bigtable.v2.ReadIterationStats.class, com.google.bigtable.v2.ReadIterationStats.Builder.class);
    }

    // Construct using com.google.bigtable.v2.ReadIterationStats.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetMemoryLayerStatsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rowsSeenCount_ = 0L;
      rowsReturnedCount_ = 0L;
      cellsSeenCount_ = 0L;
      cellsReturnedCount_ = 0L;
      memoryLayerStats_ = null;
      if (memoryLayerStatsBuilder_ != null) {
        memoryLayerStatsBuilder_.dispose();
        memoryLayerStatsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.bigtable.v2.RequestStatsProto.internal_static_google_bigtable_v2_ReadIterationStats_descriptor;
    }

    @java.lang.Override
    public com.google.bigtable.v2.ReadIterationStats getDefaultInstanceForType() {
      return com.google.bigtable.v2.ReadIterationStats.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.bigtable.v2.ReadIterationStats build() {
      com.google.bigtable.v2.ReadIterationStats result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.bigtable.v2.ReadIterationStats buildPartial() {
      com.google.bigtable.v2.ReadIterationStats result = new com.google.bigtable.v2.ReadIterationStats(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.bigtable.v2.ReadIterationStats result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rowsSeenCount_ = rowsSeenCount_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.rowsReturnedCount_ = rowsReturnedCount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cellsSeenCount_ = cellsSeenCount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cellsReturnedCount_ = cellsReturnedCount_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.memoryLayerStats_ = memoryLayerStatsBuilder_ == null
            ? memoryLayerStats_
            : memoryLayerStatsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.bigtable.v2.ReadIterationStats) {
        return mergeFrom((com.google.bigtable.v2.ReadIterationStats)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.bigtable.v2.ReadIterationStats other) {
      if (other == com.google.bigtable.v2.ReadIterationStats.getDefaultInstance()) return this;
      if (other.getRowsSeenCount() != 0L) {
        setRowsSeenCount(other.getRowsSeenCount());
      }
      if (other.getRowsReturnedCount() != 0L) {
        setRowsReturnedCount(other.getRowsReturnedCount());
      }
      if (other.getCellsSeenCount() != 0L) {
        setCellsSeenCount(other.getCellsSeenCount());
      }
      if (other.getCellsReturnedCount() != 0L) {
        setCellsReturnedCount(other.getCellsReturnedCount());
      }
      if (other.hasMemoryLayerStats()) {
        mergeMemoryLayerStats(other.getMemoryLayerStats());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              rowsSeenCount_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              rowsReturnedCount_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              cellsSeenCount_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              cellsReturnedCount_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 50: {
              input.readMessage(
                  internalGetMemoryLayerStatsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long rowsSeenCount_ ;
    /**
     * <pre>
     * The rows seen (scanned) as part of the request. This includes the count of
     * rows returned, as captured below.
     * </pre>
     *
     * <code>int64 rows_seen_count = 1;</code>
     * @return The rowsSeenCount.
     */
    @java.lang.Override
    public long getRowsSeenCount() {
      return rowsSeenCount_;
    }
    /**
     * <pre>
     * The rows seen (scanned) as part of the request. This includes the count of
     * rows returned, as captured below.
     * </pre>
     *
     * <code>int64 rows_seen_count = 1;</code>
     * @param value The rowsSeenCount to set.
     * @return This builder for chaining.
     */
    public Builder setRowsSeenCount(long value) {

      rowsSeenCount_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The rows seen (scanned) as part of the request. This includes the count of
     * rows returned, as captured below.
     * </pre>
     *
     * <code>int64 rows_seen_count = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRowsSeenCount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rowsSeenCount_ = 0L;
      onChanged();
      return this;
    }

    private long rowsReturnedCount_ ;
    /**
     * <pre>
     * The rows returned as part of the request.
     * </pre>
     *
     * <code>int64 rows_returned_count = 2;</code>
     * @return The rowsReturnedCount.
     */
    @java.lang.Override
    public long getRowsReturnedCount() {
      return rowsReturnedCount_;
    }
    /**
     * <pre>
     * The rows returned as part of the request.
     * </pre>
     *
     * <code>int64 rows_returned_count = 2;</code>
     * @param value The rowsReturnedCount to set.
     * @return This builder for chaining.
     */
    public Builder setRowsReturnedCount(long value) {

      rowsReturnedCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The rows returned as part of the request.
     * </pre>
     *
     * <code>int64 rows_returned_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRowsReturnedCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      rowsReturnedCount_ = 0L;
      onChanged();
      return this;
    }

    private long cellsSeenCount_ ;
    /**
     * <pre>
     * The cells seen (scanned) as part of the request. This includes the count of
     * cells returned, as captured below.
     * </pre>
     *
     * <code>int64 cells_seen_count = 3;</code>
     * @return The cellsSeenCount.
     */
    @java.lang.Override
    public long getCellsSeenCount() {
      return cellsSeenCount_;
    }
    /**
     * <pre>
     * The cells seen (scanned) as part of the request. This includes the count of
     * cells returned, as captured below.
     * </pre>
     *
     * <code>int64 cells_seen_count = 3;</code>
     * @param value The cellsSeenCount to set.
     * @return This builder for chaining.
     */
    public Builder setCellsSeenCount(long value) {

      cellsSeenCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The cells seen (scanned) as part of the request. This includes the count of
     * cells returned, as captured below.
     * </pre>
     *
     * <code>int64 cells_seen_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCellsSeenCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cellsSeenCount_ = 0L;
      onChanged();
      return this;
    }

    private long cellsReturnedCount_ ;
    /**
     * <pre>
     * The cells returned as part of the request.
     * </pre>
     *
     * <code>int64 cells_returned_count = 4;</code>
     * @return The cellsReturnedCount.
     */
    @java.lang.Override
    public long getCellsReturnedCount() {
      return cellsReturnedCount_;
    }
    /**
     * <pre>
     * The cells returned as part of the request.
     * </pre>
     *
     * <code>int64 cells_returned_count = 4;</code>
     * @param value The cellsReturnedCount to set.
     * @return This builder for chaining.
     */
    public Builder setCellsReturnedCount(long value) {

      cellsReturnedCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The cells returned as part of the request.
     * </pre>
     *
     * <code>int64 cells_returned_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCellsReturnedCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cellsReturnedCount_ = 0L;
      onChanged();
      return this;
    }

    private com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memoryLayerStats_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats, com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.Builder, com.google.bigtable.v2.ReadIterationStats.MemoryLayerStatsOrBuilder> memoryLayerStatsBuilder_;
    /**
     * <pre>
     * Statistics about the memory layer for this read.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
     * @return Whether the memoryLayerStats field is set.
     */
    public boolean hasMemoryLayerStats() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Statistics about the memory layer for this read.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
     * @return The memoryLayerStats.
     */
    public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats getMemoryLayerStats() {
      if (memoryLayerStatsBuilder_ == null) {
        return memoryLayerStats_ == null ? com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.getDefaultInstance() : memoryLayerStats_;
      } else {
        return memoryLayerStatsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Statistics about the memory layer for this read.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
     */
    public Builder setMemoryLayerStats(com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats value) {
      if (memoryLayerStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        memoryLayerStats_ = value;
      } else {
        memoryLayerStatsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Statistics about the memory layer for this read.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
     */
    public Builder setMemoryLayerStats(
        com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.Builder builderForValue) {
      if (memoryLayerStatsBuilder_ == null) {
        memoryLayerStats_ = builderForValue.build();
      } else {
        memoryLayerStatsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Statistics about the memory layer for this read.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
     */
    public Builder mergeMemoryLayerStats(com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats value) {
      if (memoryLayerStatsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          memoryLayerStats_ != null &&
          memoryLayerStats_ != com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.getDefaultInstance()) {
          getMemoryLayerStatsBuilder().mergeFrom(value);
        } else {
          memoryLayerStats_ = value;
        }
      } else {
        memoryLayerStatsBuilder_.mergeFrom(value);
      }
      if (memoryLayerStats_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Statistics about the memory layer for this read.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
     */
    public Builder clearMemoryLayerStats() {
      bitField0_ = (bitField0_ & ~0x00000010);
      memoryLayerStats_ = null;
      if (memoryLayerStatsBuilder_ != null) {
        memoryLayerStatsBuilder_.dispose();
        memoryLayerStatsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Statistics about the memory layer for this read.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
     */
    public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.Builder getMemoryLayerStatsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetMemoryLayerStatsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Statistics about the memory layer for this read.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
     */
    public com.google.bigtable.v2.ReadIterationStats.MemoryLayerStatsOrBuilder getMemoryLayerStatsOrBuilder() {
      if (memoryLayerStatsBuilder_ != null) {
        return memoryLayerStatsBuilder_.getMessageOrBuilder();
      } else {
        return memoryLayerStats_ == null ?
            com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.getDefaultInstance() : memoryLayerStats_;
      }
    }
    /**
     * <pre>
     * Statistics about the memory layer for this read.
     * </pre>
     *
     * <code>.google.bigtable.v2.ReadIterationStats.MemoryLayerStats memory_layer_stats = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats, com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.Builder, com.google.bigtable.v2.ReadIterationStats.MemoryLayerStatsOrBuilder> 
        internalGetMemoryLayerStatsFieldBuilder() {
      if (memoryLayerStatsBuilder_ == null) {
        memoryLayerStatsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats, com.google.bigtable.v2.ReadIterationStats.MemoryLayerStats.Builder, com.google.bigtable.v2.ReadIterationStats.MemoryLayerStatsOrBuilder>(
                getMemoryLayerStats(),
                getParentForChildren(),
                isClean());
        memoryLayerStats_ = null;
      }
      return memoryLayerStatsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:google.bigtable.v2.ReadIterationStats)
  }

  // @@protoc_insertion_point(class_scope:google.bigtable.v2.ReadIterationStats)
  private static final com.google.bigtable.v2.ReadIterationStats DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.bigtable.v2.ReadIterationStats();
  }

  public static com.google.bigtable.v2.ReadIterationStats getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReadIterationStats>
      PARSER = new com.google.protobuf.AbstractParser<ReadIterationStats>() {
    @java.lang.Override
    public ReadIterationStats parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReadIterationStats> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReadIterationStats> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.bigtable.v2.ReadIterationStats getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

