// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/session.proto
// Protobuf Java Version: 4.33.6

package com.google.bigtable.v2;

@com.google.protobuf.Generated
public interface SessionCheckAndMutateRowResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.SessionCheckAndMutateRowResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool predicate_matched = 1;</code>
   *
   * @return The predicateMatched.
   */
  boolean getPredicateMatched();
}
