/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/session.proto

package com.google.bigtable.v2;

public final class SessionProto {
  private SessionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.google.bigtable.v2.SessionProto.openSessionType);
    registry.add(com.google.bigtable.v2.SessionProto.vrpcSessionType);
    registry.add(com.google.bigtable.v2.SessionProto.rpcSessionType);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int OPEN_SESSION_TYPE_FIELD_NUMBER = 138898474;
  /**
   * <pre>
   * Only OpenSessionRequest.payload's with a type matching rpc_session_type are
   * accepted by the server, and only OpenSessionResponse.payload's with a type
   * matching rpc_session_type are accepted by the client.
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      com.google.bigtable.v2.SessionType> openSessionType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.bigtable.v2.SessionType.class,
        null);
  public static final int VRPC_SESSION_TYPE_FIELD_NUMBER = 138899157;
  /**
   * <pre>
   * Only VirtualRpcRequest.payload's with a type matching rpc_session_type are
   * accepted by the server, and only VirtualRpcResponse.payload's with a type
   * matching rpc_session_type are accepted by the client.
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.util.List<com.google.bigtable.v2.SessionType>> vrpcSessionType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.bigtable.v2.SessionType.class,
        null);
  public static final int RPC_SESSION_TYPE_FIELD_NUMBER = 137964804;
  /**
   * <pre>
   * All session service methods must set this option to indicate which
   * messages are permissible within the generic envelope.
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      com.google.bigtable.v2.SessionType> rpcSessionType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.bigtable.v2.SessionType.class,
        null);
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_GetClientConfigurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_GetClientConfigurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_LoadBalancingOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_LoadBalancingOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_LoadBalancingOptions_LeastInFlight_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_LoadBalancingOptions_LeastInFlight_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_LoadBalancingOptions_PeakEwma_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_LoadBalancingOptions_PeakEwma_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_LoadBalancingOptions_Random_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_LoadBalancingOptions_Random_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionClientConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionClientConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_DirectAccessWithFallback_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_DirectAccessWithFallback_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_DirectAccessOnly_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_DirectAccessOnly_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_CloudPathOnly_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_CloudPathOnly_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionClientConfiguration_SessionPoolConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionClientConfiguration_SessionPoolConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_TelemetryConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_TelemetryConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_ClientConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ClientConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_ClientConfiguration_PollingConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ClientConfiguration_PollingConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_OpenSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_OpenSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_BackendIdentifier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_BackendIdentifier_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_OpenSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_OpenSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_CloseSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_CloseSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_OpenTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_OpenTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_OpenTableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_OpenTableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_OpenAuthorizedViewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_OpenAuthorizedViewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_OpenAuthorizedViewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_OpenAuthorizedViewResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_OpenMaterializedViewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_OpenMaterializedViewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_OpenMaterializedViewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_OpenMaterializedViewResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_VirtualRpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_VirtualRpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_VirtualRpcRequest_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_VirtualRpcRequest_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_ClusterInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ClusterInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionRequestStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionRequestStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_VirtualRpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_VirtualRpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_TableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_TableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_TableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_TableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_AuthorizedViewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_AuthorizedViewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_AuthorizedViewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_AuthorizedViewResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_MaterializedViewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_MaterializedViewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_MaterializedViewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_MaterializedViewResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionReadRowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionReadRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionReadRowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionReadRowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionMutateRowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionMutateRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionMutateRowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionMutateRowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionParametersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionParametersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_PeerLoadUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_PeerLoadUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_GoAwayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_GoAwayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionRefreshConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionRefreshConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_bigtable_v2_SessionRefreshConfig_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SessionRefreshConfig_Metadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n google/bigtable/v2/session.proto\022\022goog" +
      "le.bigtable.v2\032\037google/api/field_behavio" +
      "r.proto\032\031google/api/resource.proto\032\035goog" +
      "le/bigtable/v2/data.proto\032&google/bigtab" +
      "le/v2/feature_flags.proto\032\"google/bigtab" +
      "le/v2/peer_info.proto\032&google/bigtable/v" +
      "2/request_stats.proto\032 google/protobuf/d" +
      "escriptor.proto\032\036google/protobuf/duratio" +
      "n.proto\032\037google/protobuf/timestamp.proto" +
      "\032\036google/rpc/error_details.proto\032\027google" +
      "/rpc/status.proto\"\202\001\n\035GetClientConfigura" +
      "tionRequest\022D\n\rinstance_name\030\001 \001(\tB-\340A\002\372" +
      "A\'\n%bigtableadmin.googleapis.com/Instanc" +
      "e\022\033\n\016app_profile_id\030\002 \001(\tB\003\340A\001\"\356\002\n\024LoadB" +
      "alancingOptions\022Q\n\017least_in_flight\030\001 \001(\013" +
      "26.google.bigtable.v2.LoadBalancingOptio" +
      "ns.LeastInFlightH\000\022F\n\tpeak_ewma\030\002 \001(\01321." +
      "google.bigtable.v2.LoadBalancingOptions." +
      "PeakEwmaH\000\022A\n\006random\030\004 \001(\0132/.google.bigt" +
      "able.v2.LoadBalancingOptions.RandomH\000\032+\n" +
      "\rLeastInFlight\022\032\n\022random_subset_size\030\001 \001" +
      "(\003\032&\n\010PeakEwma\022\032\n\022random_subset_size\030\001 \001" +
      "(\003\032\010\n\006RandomB\031\n\027load_balancing_strategy\"" +
      "\274\n\n\032SessionClientConfiguration\022\024\n\014sessio" +
      "n_load\030\001 \001(\002\022L\n\026load_balancing_options\030\002" +
      " \001(\0132(.google.bigtable.v2.LoadBalancingO" +
      "ptionsB\002\030\001\022f\n\025channel_configuration\030\003 \001(" +
      "\0132G.google.bigtable.v2.SessionClientConf" +
      "iguration.ChannelPoolConfiguration\022k\n\032se" +
      "ssion_pool_configuration\030\004 \001(\0132G.google." +
      "bigtable.v2.SessionClientConfiguration.S" +
      "essionPoolConfiguration\032\376\004\n\030ChannelPoolC" +
      "onfiguration\022\030\n\020min_server_count\030\001 \001(\005\022\030" +
      "\n\020max_server_count\030\002 \001(\005\022 \n\030per_server_s" +
      "ession_count\030\003 \001(\005\022\207\001\n\033direct_access_wit" +
      "h_fallback\030\004 \001(\0132`.google.bigtable.v2.Se" +
      "ssionClientConfiguration.ChannelPoolConf" +
      "iguration.DirectAccessWithFallbackH\000\022v\n\022" +
      "direct_access_only\030\005 \001(\0132X.google.bigtab" +
      "le.v2.SessionClientConfiguration.Channel" +
      "PoolConfiguration.DirectAccessOnlyH\000\022p\n\017" +
      "cloud_path_only\030\006 \001(\0132U.google.bigtable." +
      "v2.SessionClientConfiguration.ChannelPoo" +
      "lConfiguration.CloudPathOnlyH\000\032k\n\030Direct" +
      "AccessWithFallback\022\034\n\024error_rate_thresho" +
      "ld\030\001 \001(\002\0221\n\016check_interval\030\002 \001(\0132\031.googl" +
      "e.protobuf.Duration\032\022\n\020DirectAccessOnly\032" +
      "\017\n\rCloudPathOnlyB\006\n\004mode\032\343\002\n\030SessionPool" +
      "Configuration\022\020\n\010headroom\030\001 \001(\002\022\031\n\021min_s" +
      "ession_count\030\002 \001(\005\022\031\n\021max_session_count\030" +
      "\003 \001(\005\022 \n\030new_session_queue_length\030\004 \001(\005\022" +
      "#\n\033new_session_creation_budget\030\005 \001(\005\022?\n\034" +
      "new_session_creation_penalty\030\006 \001(\0132\031.goo" +
      "gle.protobuf.Duration\022-\n%consecutive_ses" +
      "sion_failure_threshold\030\010 \001(\005\022H\n\026load_bal" +
      "ancing_options\030\t \001(\0132(.google.bigtable.v" +
      "2.LoadBalancingOptions\"\255\001\n\026TelemetryConf" +
      "iguration\022I\n\017debug_tag_level\030\001 \001(\01620.goo" +
      "gle.bigtable.v2.TelemetryConfiguration.L" +
      "evel\"H\n\005Level\022\025\n\021LEVEL_UNSPECIFIED\020\000\022\t\n\005" +
      "DEBUG\020\001\022\010\n\004INFO\020\002\022\010\n\004WARN\020\003\022\t\n\005ERROR\020\004\"\217" +
      "\004\n\023ClientConfiguration\022M\n\025session_config" +
      "uration\030\002 \001(\0132..google.bigtable.v2.Sessi" +
      "onClientConfiguration\022\026\n\014stop_polling\030\003 " +
      "\001(\010H\000\0229\n\020polling_interval\030\004 \001(\0132\031.google" +
      ".protobuf.DurationB\002\030\001H\000\022]\n\025polling_conf" +
      "iguration\030\005 \001(\0132<.google.bigtable.v2.Cli" +
      "entConfiguration.PollingConfigurationH\000\022" +
      "K\n\027telemetry_configuration\030\006 \001(\0132*.googl" +
      "e.bigtable.v2.TelemetryConfiguration\032\236\001\n" +
      "\024PollingConfiguration\0223\n\020polling_interva" +
      "l\030\001 \001(\0132\031.google.protobuf.Duration\0224\n\021va" +
      "lidity_duration\030\002 \001(\0132\031.google.protobuf." +
      "Duration\022\033\n\023max_rpc_retry_count\030\006 \001(\005B\t\n" +
      "\007polling\"\333\001\n\016SessionRequest\022>\n\014open_sess" +
      "ion\030\001 \001(\0132&.google.bigtable.v2.OpenSessi" +
      "onRequestH\000\022@\n\rclose_session\030\002 \001(\0132\'.goo" +
      "gle.bigtable.v2.CloseSessionRequestH\000\022<\n" +
      "\013virtual_rpc\030\003 \001(\0132%.google.bigtable.v2." +
      "VirtualRpcRequestH\000B\t\n\007payload\"\230\004\n\017Sessi" +
      "onResponse\022?\n\014open_session\030\001 \001(\0132\'.googl" +
      "e.bigtable.v2.OpenSessionResponseH\000\022=\n\013v" +
      "irtual_rpc\030\002 \001(\0132&.google.bigtable.v2.Vi" +
      "rtualRpcResponseH\000\0222\n\005error\030\003 \001(\0132!.goog" +
      "le.bigtable.v2.ErrorResponseH\000\022K\n\022sessio" +
      "n_parameters\030\004 \001(\0132-.google.bigtable.v2." +
      "SessionParametersResponseH\000\022:\n\theartbeat" +
      "\030\005 \001(\0132%.google.bigtable.v2.HeartbeatRes" +
      "ponseH\000\0225\n\007go_away\030\006 \001(\0132\".google.bigtab" +
      "le.v2.GoAwayResponseH\000\022J\n\026session_refres" +
      "h_config\030\007 \001(\0132(.google.bigtable.v2.Sess" +
      "ionRefreshConfigH\000\022:\n\016peer_load_info\030\010 \001" +
      "(\0132 .google.bigtable.v2.PeerLoadInfoH\000B\t" +
      "\n\007payload\"\270\001\n\022OpenSessionRequest\022\030\n\020prot" +
      "ocol_version\030\001 \001(\003\022/\n\005flags\030\002 \001(\0132 .goog" +
      "le.bigtable.v2.FeatureFlags\022.\n&consecuti" +
      "ve_failed_connection_attempts\030\003 \001(\003\022\026\n\016r" +
      "outing_cookie\030\004 \001(\014\022\017\n\007payload\030\005 \001(\014\"s\n\021" +
      "BackendIdentifier\022\032\n\022google_frontend_id\030" +
      "\001 \001(\003\022\037\n\027application_frontend_id\030\002 \001(\003\022!" +
      "\n\031application_frontend_zone\030\003 \001(\t\"^\n\023Ope" +
      "nSessionResponse\0226\n\007backend\030\002 \001(\0132%.goog" +
      "le.bigtable.v2.BackendIdentifier\022\017\n\007payl" +
      "oad\030\001 \001(\014\"\333\002\n\023CloseSessionRequest\022J\n\006rea" +
      "son\030\001 \001(\0162:.google.bigtable.v2.CloseSess" +
      "ionRequest.CloseSessionReason\022\023\n\013descrip" +
      "tion\030\002 \001(\t\"\342\001\n\022CloseSessionReason\022\036\n\032CLO" +
      "SE_SESSION_REASON_UNSET\020\000\022\037\n\033CLOSE_SESSI" +
      "ON_REASON_GOAWAY\020\001\022\036\n\032CLOSE_SESSION_REAS" +
      "ON_ERROR\020\002\022\035\n\031CLOSE_SESSION_REASON_USER\020" +
      "\003\022!\n\035CLOSE_SESSION_REASON_DOWNSIZE\020\004\022)\n%" +
      "CLOSE_SESSION_REASON_MISSED_HEARTBEAT\020\005\"" +
      "\365\001\n\020OpenTableRequest\022\022\n\ntable_name\030\001 \001(\t" +
      "\022\026\n\016app_profile_id\030\002 \001(\t\022C\n\npermission\030\003" +
      " \001(\0162/.google.bigtable.v2.OpenTableReque" +
      "st.Permission\"h\n\nPermission\022\024\n\020PERMISSIO" +
      "N_UNSET\020\000\022\023\n\017PERMISSION_READ\020\001\022\024\n\020PERMIS" +
      "SION_WRITE\020\002\022\031\n\025PERMISSION_READ_WRITE\020\003:" +
      "\006\320\302\355\221\004\001\"\033\n\021OpenTableResponse:\006\320\302\355\221\004\001\"\221\002\n" +
      "\031OpenAuthorizedViewRequest\022\034\n\024authorized" +
      "_view_name\030\001 \001(\t\022\026\n\016app_profile_id\030\002 \001(\t" +
      "\022L\n\npermission\030\003 \001(\01628.google.bigtable.v" +
      "2.OpenAuthorizedViewRequest.Permission\"h" +
      "\n\nPermission\022\024\n\020PERMISSION_UNSET\020\000\022\023\n\017PE" +
      "RMISSION_READ\020\001\022\024\n\020PERMISSION_WRITE\020\002\022\031\n" +
      "\025PERMISSION_READ_WRITE\020\003:\006\320\302\355\221\004\002\"$\n\032Open" +
      "AuthorizedViewResponse:\006\320\302\355\221\004\002\"\346\001\n\033OpenM" +
      "aterializedViewRequest\022\036\n\026materialized_v" +
      "iew_name\030\001 \001(\t\022\026\n\016app_profile_id\030\002 \001(\t\022N" +
      "\n\npermission\030\003 \001(\0162:.google.bigtable.v2." +
      "OpenMaterializedViewRequest.Permission\"7" +
      "\n\nPermission\022\024\n\020PERMISSION_UNSET\020\000\022\023\n\017PE" +
      "RMISSION_READ\020\001:\006\320\302\355\221\004\003\"&\n\034OpenMateriali" +
      "zedViewResponse:\006\320\302\355\221\004\003\"\217\002\n\021VirtualRpcRe" +
      "quest\022\016\n\006rpc_id\030\001 \001(\003\022+\n\010deadline\030\002 \001(\0132" +
      "\031.google.protobuf.Duration\022@\n\010metadata\030\003" +
      " \001(\0132..google.bigtable.v2.VirtualRpcRequ" +
      "est.Metadata\022\017\n\007payload\030\004 \001(\014\032j\n\010Metadat" +
      "a\022\026\n\016attempt_number\030\001 \001(\003\0221\n\rattempt_sta" +
      "rt\030\002 \001(\0132\032.google.protobuf.Timestamp\022\023\n\013" +
      "traceparent\030\003 \001(\t\"9\n\022ClusterInformation\022" +
      "\022\n\ncluster_id\030\001 \001(\t\022\017\n\007zone_id\030\002 \001(\t\"I\n\023" +
      "SessionRequestStats\0222\n\017backend_latency\030\001" +
      " \001(\0132\031.google.protobuf.Duration\"\253\001\n\022Virt" +
      "ualRpcResponse\022\016\n\006rpc_id\030\001 \001(\003\022<\n\014cluste" +
      "r_info\030\002 \001(\0132&.google.bigtable.v2.Cluste" +
      "rInformation\0226\n\005stats\030\004 \001(\0132\'.google.big" +
      "table.v2.SessionRequestStats\022\017\n\007payload\030" +
      "\003 \001(\014\"\254\001\n\rErrorResponse\022\016\n\006rpc_id\030\001 \001(\003\022" +
      "<\n\014cluster_info\030\002 \001(\0132&.google.bigtable." +
      "v2.ClusterInformation\022\"\n\006status\030\003 \001(\0132\022." +
      "google.rpc.Status\022)\n\nretry_info\030\004 \001(\0132\025." +
      "google.rpc.RetryInfo\"\244\001\n\014TableRequest\022=\n" +
      "\010read_row\030\001 \001(\0132).google.bigtable.v2.Ses" +
      "sionReadRowRequestH\000\022A\n\nmutate_row\030\002 \001(\013" +
      "2+.google.bigtable.v2.SessionMutateRowRe" +
      "questH\000:\007\252\355\355\221\004\001\001B\t\n\007payload\"\247\001\n\rTableRes" +
      "ponse\022>\n\010read_row\030\001 \001(\0132*.google.bigtabl" +
      "e.v2.SessionReadRowResponseH\000\022B\n\nmutate_" +
      "row\030\002 \001(\0132,.google.bigtable.v2.SessionMu" +
      "tateRowResponseH\000:\007\252\355\355\221\004\001\001B\t\n\007payload\"\255\001" +
      "\n\025AuthorizedViewRequest\022=\n\010read_row\030\001 \001(" +
      "\0132).google.bigtable.v2.SessionReadRowReq" +
      "uestH\000\022A\n\nmutate_row\030\002 \001(\0132+.google.bigt" +
      "able.v2.SessionMutateRowRequestH\000:\007\252\355\355\221\004" +
      "\001\002B\t\n\007payload\"\260\001\n\026AuthorizedViewResponse" +
      "\022>\n\010read_row\030\001 \001(\0132*.google.bigtable.v2." +
      "SessionReadRowResponseH\000\022B\n\nmutate_row\030\002" +
      " \001(\0132,.google.bigtable.v2.SessionMutateR" +
      "owResponseH\000:\007\252\355\355\221\004\001\002B\t\n\007payload\"l\n\027Mate" +
      "rializedViewRequest\022=\n\010read_row\030\001 \001(\0132)." +
      "google.bigtable.v2.SessionReadRowRequest" +
      "H\000:\007\252\355\355\221\004\001\003B\t\n\007payload\"n\n\030MaterializedVi" +
      "ewResponse\022>\n\010read_row\030\001 \001(\0132*.google.bi" +
      "gtable.v2.SessionReadRowResponseH\000:\007\252\355\355\221" +
      "\004\001\003B\t\n\007payload\"S\n\025SessionReadRowRequest\022" +
      "\013\n\003key\030\001 \001(\014\022-\n\006filter\030\002 \001(\0132\035.google.bi" +
      "gtable.v2.RowFilter\"o\n\026SessionReadRowRes" +
      "ponse\022$\n\003row\030\001 \001(\0132\027.google.bigtable.v2." +
      "Row\022/\n\005stats\030\002 \001(\0132 .google.bigtable.v2." +
      "RequestStats\"W\n\027SessionMutateRowRequest\022" +
      "\013\n\003key\030\001 \001(\014\022/\n\tmutations\030\002 \003(\0132\034.google" +
      ".bigtable.v2.Mutation\"\032\n\030SessionMutateRo" +
      "wResponse\"J\n\031SessionParametersResponse\022-" +
      "\n\nkeep_alive\030\001 \001(\0132\031.google.protobuf.Dur" +
      "ation\"\023\n\021HeartbeatResponse\"M\n\026PeerLoadUp" +
      "dateResponse\0223\n\tload_info\030\001 \001(\0132 .google" +
      ".bigtable.v2.PeerLoadInfo\"S\n\016GoAwayRespo" +
      "nse\022\016\n\006reason\030\001 \001(\t\022\023\n\013description\030\002 \001(\t" +
      "\022\034\n\024last_rpc_id_admitted\030\003 \001(\003\"\332\001\n\024Sessi" +
      "onRefreshConfig\022F\n\026optimized_open_reques" +
      "t\030\001 \001(\0132&.google.bigtable.v2.OpenSession" +
      "Request\022H\n\010metadata\030\002 \003(\01321.google.bigta" +
      "ble.v2.SessionRefreshConfig.MetadataB\003\340A" +
      "\003\0320\n\010Metadata\022\020\n\003key\030\001 \001(\tB\003\340A\003\022\022\n\005value" +
      "\030\002 \001(\014B\003\340A\003*\233\001\n\013SessionType\022\026\n\022SESSION_T" +
      "YPE_UNSET\020\000\022\026\n\022SESSION_TYPE_TABLE\020\001\022 \n\034S" +
      "ESSION_TYPE_AUTHORIZED_VIEW\020\002\022\"\n\036SESSION" +
      "_TYPE_MATERIALIZED_VIEW\020\003\022\026\n\021SESSION_TYP" +
      "E_TEST\020\217N:^\n\021open_session_type\022\037.google." +
      "protobuf.MessageOptions\030\252\330\235B \001(\0162\037.googl" +
      "e.bigtable.v2.SessionType:^\n\021vrpc_sessio" +
      "n_type\022\037.google.protobuf.MessageOptions\030" +
      "\325\335\235B \003(\0162\037.google.bigtable.v2.SessionTyp" +
      "e:\\\n\020rpc_session_type\022\036.google.protobuf." +
      "MethodOptions\030\204\332\344A \001(\0162\037.google.bigtable" +
      ".v2.SessionTypeB\266\001\n\026com.google.bigtable." +
      "v2B\014SessionProtoP\001Z8cloud.google.com/go/" +
      "bigtable/apiv2/bigtablepb;bigtablepb\252\002\030G" +
      "oogle.Cloud.Bigtable.V2\312\002\030Google\\Cloud\\B" +
      "igtable\\V2\352\002\033Google::Cloud::Bigtable::V2" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.bigtable.v2.DataProto.getDescriptor(),
          com.google.bigtable.v2.FeatureFlagsProto.getDescriptor(),
          com.google.bigtable.v2.PeerInfoProto.getDescriptor(),
          com.google.bigtable.v2.RequestStatsProto.getDescriptor(),
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.rpc.ErrorDetailsProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        });
    internal_static_google_bigtable_v2_GetClientConfigurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_bigtable_v2_GetClientConfigurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_GetClientConfigurationRequest_descriptor,
        new java.lang.String[] { "InstanceName", "AppProfileId", });
    internal_static_google_bigtable_v2_LoadBalancingOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_bigtable_v2_LoadBalancingOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_LoadBalancingOptions_descriptor,
        new java.lang.String[] { "LeastInFlight", "PeakEwma", "Random", "LoadBalancingStrategy", });
    internal_static_google_bigtable_v2_LoadBalancingOptions_LeastInFlight_descriptor =
      internal_static_google_bigtable_v2_LoadBalancingOptions_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_LoadBalancingOptions_LeastInFlight_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_LoadBalancingOptions_LeastInFlight_descriptor,
        new java.lang.String[] { "RandomSubsetSize", });
    internal_static_google_bigtable_v2_LoadBalancingOptions_PeakEwma_descriptor =
      internal_static_google_bigtable_v2_LoadBalancingOptions_descriptor.getNestedTypes().get(1);
    internal_static_google_bigtable_v2_LoadBalancingOptions_PeakEwma_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_LoadBalancingOptions_PeakEwma_descriptor,
        new java.lang.String[] { "RandomSubsetSize", });
    internal_static_google_bigtable_v2_LoadBalancingOptions_Random_descriptor =
      internal_static_google_bigtable_v2_LoadBalancingOptions_descriptor.getNestedTypes().get(2);
    internal_static_google_bigtable_v2_LoadBalancingOptions_Random_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_LoadBalancingOptions_Random_descriptor,
        new java.lang.String[] { });
    internal_static_google_bigtable_v2_SessionClientConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_bigtable_v2_SessionClientConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionClientConfiguration_descriptor,
        new java.lang.String[] { "SessionLoad", "LoadBalancingOptions", "ChannelConfiguration", "SessionPoolConfiguration", });
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_descriptor =
      internal_static_google_bigtable_v2_SessionClientConfiguration_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_descriptor,
        new java.lang.String[] { "MinServerCount", "MaxServerCount", "PerServerSessionCount", "DirectAccessWithFallback", "DirectAccessOnly", "CloudPathOnly", "Mode", });
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_DirectAccessWithFallback_descriptor =
      internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_DirectAccessWithFallback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_DirectAccessWithFallback_descriptor,
        new java.lang.String[] { "ErrorRateThreshold", "CheckInterval", });
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_DirectAccessOnly_descriptor =
      internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_descriptor.getNestedTypes().get(1);
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_DirectAccessOnly_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_DirectAccessOnly_descriptor,
        new java.lang.String[] { });
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_CloudPathOnly_descriptor =
      internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_descriptor.getNestedTypes().get(2);
    internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_CloudPathOnly_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionClientConfiguration_ChannelPoolConfiguration_CloudPathOnly_descriptor,
        new java.lang.String[] { });
    internal_static_google_bigtable_v2_SessionClientConfiguration_SessionPoolConfiguration_descriptor =
      internal_static_google_bigtable_v2_SessionClientConfiguration_descriptor.getNestedTypes().get(1);
    internal_static_google_bigtable_v2_SessionClientConfiguration_SessionPoolConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionClientConfiguration_SessionPoolConfiguration_descriptor,
        new java.lang.String[] { "Headroom", "MinSessionCount", "MaxSessionCount", "NewSessionQueueLength", "NewSessionCreationBudget", "NewSessionCreationPenalty", "ConsecutiveSessionFailureThreshold", "LoadBalancingOptions", });
    internal_static_google_bigtable_v2_TelemetryConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_bigtable_v2_TelemetryConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_TelemetryConfiguration_descriptor,
        new java.lang.String[] { "DebugTagLevel", });
    internal_static_google_bigtable_v2_ClientConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_bigtable_v2_ClientConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_ClientConfiguration_descriptor,
        new java.lang.String[] { "SessionConfiguration", "StopPolling", "PollingInterval", "PollingConfiguration", "TelemetryConfiguration", "Polling", });
    internal_static_google_bigtable_v2_ClientConfiguration_PollingConfiguration_descriptor =
      internal_static_google_bigtable_v2_ClientConfiguration_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_ClientConfiguration_PollingConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_ClientConfiguration_PollingConfiguration_descriptor,
        new java.lang.String[] { "PollingInterval", "ValidityDuration", "MaxRpcRetryCount", });
    internal_static_google_bigtable_v2_SessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_bigtable_v2_SessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionRequest_descriptor,
        new java.lang.String[] { "OpenSession", "CloseSession", "VirtualRpc", "Payload", });
    internal_static_google_bigtable_v2_SessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_bigtable_v2_SessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionResponse_descriptor,
        new java.lang.String[] { "OpenSession", "VirtualRpc", "Error", "SessionParameters", "Heartbeat", "GoAway", "SessionRefreshConfig", "PeerLoadInfo", "Payload", });
    internal_static_google_bigtable_v2_OpenSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_bigtable_v2_OpenSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_OpenSessionRequest_descriptor,
        new java.lang.String[] { "ProtocolVersion", "Flags", "ConsecutiveFailedConnectionAttempts", "RoutingCookie", "Payload", });
    internal_static_google_bigtable_v2_BackendIdentifier_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_bigtable_v2_BackendIdentifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_BackendIdentifier_descriptor,
        new java.lang.String[] { "GoogleFrontendId", "ApplicationFrontendId", "ApplicationFrontendZone", });
    internal_static_google_bigtable_v2_OpenSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_bigtable_v2_OpenSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_OpenSessionResponse_descriptor,
        new java.lang.String[] { "Backend", "Payload", });
    internal_static_google_bigtable_v2_CloseSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_bigtable_v2_CloseSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_CloseSessionRequest_descriptor,
        new java.lang.String[] { "Reason", "Description", });
    internal_static_google_bigtable_v2_OpenTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_bigtable_v2_OpenTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_OpenTableRequest_descriptor,
        new java.lang.String[] { "TableName", "AppProfileId", "Permission", });
    internal_static_google_bigtable_v2_OpenTableResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_bigtable_v2_OpenTableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_OpenTableResponse_descriptor,
        new java.lang.String[] { });
    internal_static_google_bigtable_v2_OpenAuthorizedViewRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_bigtable_v2_OpenAuthorizedViewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_OpenAuthorizedViewRequest_descriptor,
        new java.lang.String[] { "AuthorizedViewName", "AppProfileId", "Permission", });
    internal_static_google_bigtable_v2_OpenAuthorizedViewResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_bigtable_v2_OpenAuthorizedViewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_OpenAuthorizedViewResponse_descriptor,
        new java.lang.String[] { });
    internal_static_google_bigtable_v2_OpenMaterializedViewRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_bigtable_v2_OpenMaterializedViewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_OpenMaterializedViewRequest_descriptor,
        new java.lang.String[] { "MaterializedViewName", "AppProfileId", "Permission", });
    internal_static_google_bigtable_v2_OpenMaterializedViewResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_bigtable_v2_OpenMaterializedViewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_OpenMaterializedViewResponse_descriptor,
        new java.lang.String[] { });
    internal_static_google_bigtable_v2_VirtualRpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_bigtable_v2_VirtualRpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_VirtualRpcRequest_descriptor,
        new java.lang.String[] { "RpcId", "Deadline", "Metadata", "Payload", });
    internal_static_google_bigtable_v2_VirtualRpcRequest_Metadata_descriptor =
      internal_static_google_bigtable_v2_VirtualRpcRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_VirtualRpcRequest_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_VirtualRpcRequest_Metadata_descriptor,
        new java.lang.String[] { "AttemptNumber", "AttemptStart", "Traceparent", });
    internal_static_google_bigtable_v2_ClusterInformation_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_bigtable_v2_ClusterInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_ClusterInformation_descriptor,
        new java.lang.String[] { "ClusterId", "ZoneId", });
    internal_static_google_bigtable_v2_SessionRequestStats_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_bigtable_v2_SessionRequestStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionRequestStats_descriptor,
        new java.lang.String[] { "BackendLatency", });
    internal_static_google_bigtable_v2_VirtualRpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_google_bigtable_v2_VirtualRpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_VirtualRpcResponse_descriptor,
        new java.lang.String[] { "RpcId", "ClusterInfo", "Stats", "Payload", });
    internal_static_google_bigtable_v2_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_google_bigtable_v2_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_ErrorResponse_descriptor,
        new java.lang.String[] { "RpcId", "ClusterInfo", "Status", "RetryInfo", });
    internal_static_google_bigtable_v2_TableRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_google_bigtable_v2_TableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_TableRequest_descriptor,
        new java.lang.String[] { "ReadRow", "MutateRow", "Payload", });
    internal_static_google_bigtable_v2_TableResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_google_bigtable_v2_TableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_TableResponse_descriptor,
        new java.lang.String[] { "ReadRow", "MutateRow", "Payload", });
    internal_static_google_bigtable_v2_AuthorizedViewRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_google_bigtable_v2_AuthorizedViewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_AuthorizedViewRequest_descriptor,
        new java.lang.String[] { "ReadRow", "MutateRow", "Payload", });
    internal_static_google_bigtable_v2_AuthorizedViewResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_google_bigtable_v2_AuthorizedViewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_AuthorizedViewResponse_descriptor,
        new java.lang.String[] { "ReadRow", "MutateRow", "Payload", });
    internal_static_google_bigtable_v2_MaterializedViewRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_google_bigtable_v2_MaterializedViewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_MaterializedViewRequest_descriptor,
        new java.lang.String[] { "ReadRow", "Payload", });
    internal_static_google_bigtable_v2_MaterializedViewResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_google_bigtable_v2_MaterializedViewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_MaterializedViewResponse_descriptor,
        new java.lang.String[] { "ReadRow", "Payload", });
    internal_static_google_bigtable_v2_SessionReadRowRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_google_bigtable_v2_SessionReadRowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionReadRowRequest_descriptor,
        new java.lang.String[] { "Key", "Filter", });
    internal_static_google_bigtable_v2_SessionReadRowResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_google_bigtable_v2_SessionReadRowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionReadRowResponse_descriptor,
        new java.lang.String[] { "Row", "Stats", });
    internal_static_google_bigtable_v2_SessionMutateRowRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_google_bigtable_v2_SessionMutateRowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionMutateRowRequest_descriptor,
        new java.lang.String[] { "Key", "Mutations", });
    internal_static_google_bigtable_v2_SessionMutateRowResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_google_bigtable_v2_SessionMutateRowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionMutateRowResponse_descriptor,
        new java.lang.String[] { });
    internal_static_google_bigtable_v2_SessionParametersResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_google_bigtable_v2_SessionParametersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionParametersResponse_descriptor,
        new java.lang.String[] { "KeepAlive", });
    internal_static_google_bigtable_v2_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_google_bigtable_v2_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_HeartbeatResponse_descriptor,
        new java.lang.String[] { });
    internal_static_google_bigtable_v2_PeerLoadUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_google_bigtable_v2_PeerLoadUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_PeerLoadUpdateResponse_descriptor,
        new java.lang.String[] { "LoadInfo", });
    internal_static_google_bigtable_v2_GoAwayResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_google_bigtable_v2_GoAwayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_GoAwayResponse_descriptor,
        new java.lang.String[] { "Reason", "Description", "LastRpcIdAdmitted", });
    internal_static_google_bigtable_v2_SessionRefreshConfig_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_google_bigtable_v2_SessionRefreshConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionRefreshConfig_descriptor,
        new java.lang.String[] { "OptimizedOpenRequest", "Metadata", });
    internal_static_google_bigtable_v2_SessionRefreshConfig_Metadata_descriptor =
      internal_static_google_bigtable_v2_SessionRefreshConfig_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_SessionRefreshConfig_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_bigtable_v2_SessionRefreshConfig_Metadata_descriptor,
        new java.lang.String[] { "Key", "Value", });
    openSessionType.internalInit(descriptor.getExtensions().get(0));
    vrpcSessionType.internalInit(descriptor.getExtensions().get(1));
    rpcSessionType.internalInit(descriptor.getExtensions().get(2));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.bigtable.v2.SessionProto.openSessionType);
    registry.add(com.google.bigtable.v2.SessionProto.vrpcSessionType);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.bigtable.v2.DataProto.getDescriptor();
    com.google.bigtable.v2.FeatureFlagsProto.getDescriptor();
    com.google.bigtable.v2.PeerInfoProto.getDescriptor();
    com.google.bigtable.v2.RequestStatsProto.getDescriptor();
    com.google.protobuf.DescriptorProtos.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.ErrorDetailsProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
