// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/session.proto
// Protobuf Java Version: 4.33.6

package com.google.bigtable.v2;

/**
 *
 *
 * <pre>
 * Supported session types.
 * </pre>
 *
 * Protobuf enum {@code google.bigtable.v2.SessionType}
 */
@com.google.protobuf.Generated
public enum SessionType implements com.google.protobuf.ProtocolMessageEnum {
  /** <code>SESSION_TYPE_UNSET = 0;</code> */
  SESSION_TYPE_UNSET(0),
  /** <code>SESSION_TYPE_TABLE = 1;</code> */
  SESSION_TYPE_TABLE(1),
  /** <code>SESSION_TYPE_AUTHORIZED_VIEW = 2;</code> */
  SESSION_TYPE_AUTHORIZED_VIEW(2),
  /** <code>SESSION_TYPE_MATERIALIZED_VIEW = 3;</code> */
  SESSION_TYPE_MATERIALIZED_VIEW(3),
  /**
   *
   *
   * <pre>
   * For internal protocol testing only.
   * </pre>
   *
   * <code>SESSION_TYPE_TEST = 9999;</code>
   */
  SESSION_TYPE_TEST(9999),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 6,
        /* suffix= */ "",
        "SessionType");
  }

  /** <code>SESSION_TYPE_UNSET = 0;</code> */
  public static final int SESSION_TYPE_UNSET_VALUE = 0;

  /** <code>SESSION_TYPE_TABLE = 1;</code> */
  public static final int SESSION_TYPE_TABLE_VALUE = 1;

  /** <code>SESSION_TYPE_AUTHORIZED_VIEW = 2;</code> */
  public static final int SESSION_TYPE_AUTHORIZED_VIEW_VALUE = 2;

  /** <code>SESSION_TYPE_MATERIALIZED_VIEW = 3;</code> */
  public static final int SESSION_TYPE_MATERIALIZED_VIEW_VALUE = 3;

  /**
   *
   *
   * <pre>
   * For internal protocol testing only.
   * </pre>
   *
   * <code>SESSION_TYPE_TEST = 9999;</code>
   */
  public static final int SESSION_TYPE_TEST_VALUE = 9999;

  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SessionType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SessionType forNumber(int value) {
    switch (value) {
      case 0:
        return SESSION_TYPE_UNSET;
      case 1:
        return SESSION_TYPE_TABLE;
      case 2:
        return SESSION_TYPE_AUTHORIZED_VIEW;
      case 3:
        return SESSION_TYPE_MATERIALIZED_VIEW;
      case 9999:
        return SESSION_TYPE_TEST;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SessionType> internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<SessionType> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<SessionType>() {
        public SessionType findValueByNumber(int number) {
          return SessionType.forNumber(number);
        }
      };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }

  public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
    return getDescriptor();
  }

  public static com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
    return com.google.bigtable.v2.SessionProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final SessionType[] VALUES = values();

  public static SessionType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SessionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.bigtable.v2.SessionType)
}
