// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/bigtable.proto
// Protobuf Java Version: 4.33.6

package com.google.bigtable.v2;

/**
 * <pre>
 * Response message for Bigtable.SimpleExecuteQuery
 * </pre>
 *
 * Protobuf type {@code google.bigtable.v2.SimpleExecuteQueryResponse}
 */
@com.google.protobuf.Generated
public final class SimpleExecuteQueryResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.bigtable.v2.SimpleExecuteQueryResponse)
    SimpleExecuteQueryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 6,
      /* suffix= */ "",
      "SimpleExecuteQueryResponse");
  }
  // Use SimpleExecuteQueryResponse.newBuilder() to construct.
  private SimpleExecuteQueryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SimpleExecuteQueryResponse() {
    rows_ = java.util.Collections.emptyList();
    nextPageToken_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.bigtable.v2.BigtableProto.internal_static_google_bigtable_v2_SimpleExecuteQueryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.bigtable.v2.BigtableProto.internal_static_google_bigtable_v2_SimpleExecuteQueryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.bigtable.v2.SimpleExecuteQueryResponse.class, com.google.bigtable.v2.SimpleExecuteQueryResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SCHEMA_FIELD_NUMBER = 1;
  private com.google.bigtable.v2.ProtoSchema schema_;
  /**
   * <pre>
   * Schema of the columns in the result set.
   * </pre>
   *
   * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
   * @return Whether the schema field is set.
   */
  @java.lang.Override
  public boolean hasSchema() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Schema of the columns in the result set.
   * </pre>
   *
   * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
   * @return The schema.
   */
  @java.lang.Override
  public com.google.bigtable.v2.ProtoSchema getSchema() {
    return schema_ == null ? com.google.bigtable.v2.ProtoSchema.getDefaultInstance() : schema_;
  }
  /**
   * <pre>
   * Schema of the columns in the result set.
   * </pre>
   *
   * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
   */
  @java.lang.Override
  public com.google.bigtable.v2.ProtoSchemaOrBuilder getSchemaOrBuilder() {
    return schema_ == null ? com.google.bigtable.v2.ProtoSchema.getDefaultInstance() : schema_;
  }

  public static final int ROWS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.google.bigtable.v2.ArrayValue> rows_;
  /**
   * <pre>
   * The rows in the result set wherein each row contains values with schema
   * matching the `schema` field above.
   * </pre>
   *
   * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.bigtable.v2.ArrayValue> getRowsList() {
    return rows_;
  }
  /**
   * <pre>
   * The rows in the result set wherein each row contains values with schema
   * matching the `schema` field above.
   * </pre>
   *
   * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.bigtable.v2.ArrayValueOrBuilder> 
      getRowsOrBuilderList() {
    return rows_;
  }
  /**
   * <pre>
   * The rows in the result set wherein each row contains values with schema
   * matching the `schema` field above.
   * </pre>
   *
   * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
   */
  @java.lang.Override
  public int getRowsCount() {
    return rows_.size();
  }
  /**
   * <pre>
   * The rows in the result set wherein each row contains values with schema
   * matching the `schema` field above.
   * </pre>
   *
   * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
   */
  @java.lang.Override
  public com.google.bigtable.v2.ArrayValue getRows(int index) {
    return rows_.get(index);
  }
  /**
   * <pre>
   * The rows in the result set wherein each row contains values with schema
   * matching the `schema` field above.
   * </pre>
   *
   * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
   */
  @java.lang.Override
  public com.google.bigtable.v2.ArrayValueOrBuilder getRowsOrBuilder(
      int index) {
    return rows_.get(index);
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nextPageToken_ = "";
  /**
   * <pre>
   * Optional. A token that can be sent as `page_token` to retrieve the next
   * rows in the result set. If this field is omitted, there are no subsequent
   * rows.
   * </pre>
   *
   * <code>string next_page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The nextPageToken.
   */
  @java.lang.Override
  public java.lang.String getNextPageToken() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextPageToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. A token that can be sent as `page_token` to retrieve the next
   * rows in the result set. If this field is omitted, there are no subsequent
   * rows.
   * </pre>
   *
   * <code>string next_page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The bytes for nextPageToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextPageTokenBytes() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextPageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getSchema());
    }
    for (int i = 0; i < rows_.size(); i++) {
      output.writeMessage(2, rows_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextPageToken_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, nextPageToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSchema());
    }
    for (int i = 0; i < rows_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, rows_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextPageToken_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, nextPageToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.bigtable.v2.SimpleExecuteQueryResponse)) {
      return super.equals(obj);
    }
    com.google.bigtable.v2.SimpleExecuteQueryResponse other = (com.google.bigtable.v2.SimpleExecuteQueryResponse) obj;

    if (hasSchema() != other.hasSchema()) return false;
    if (hasSchema()) {
      if (!getSchema()
          .equals(other.getSchema())) return false;
    }
    if (!getRowsList()
        .equals(other.getRowsList())) return false;
    if (!getNextPageToken()
        .equals(other.getNextPageToken())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSchema()) {
      hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + getSchema().hashCode();
    }
    if (getRowsCount() > 0) {
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRowsList().hashCode();
    }
    hash = (37 * hash) + NEXT_PAGE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getNextPageToken().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.bigtable.v2.SimpleExecuteQueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.bigtable.v2.SimpleExecuteQueryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response message for Bigtable.SimpleExecuteQuery
   * </pre>
   *
   * Protobuf type {@code google.bigtable.v2.SimpleExecuteQueryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.bigtable.v2.SimpleExecuteQueryResponse)
      com.google.bigtable.v2.SimpleExecuteQueryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.bigtable.v2.BigtableProto.internal_static_google_bigtable_v2_SimpleExecuteQueryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.bigtable.v2.BigtableProto.internal_static_google_bigtable_v2_SimpleExecuteQueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.bigtable.v2.SimpleExecuteQueryResponse.class, com.google.bigtable.v2.SimpleExecuteQueryResponse.Builder.class);
    }

    // Construct using com.google.bigtable.v2.SimpleExecuteQueryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSchemaFieldBuilder();
        internalGetRowsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      schema_ = null;
      if (schemaBuilder_ != null) {
        schemaBuilder_.dispose();
        schemaBuilder_ = null;
      }
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
      } else {
        rows_ = null;
        rowsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      nextPageToken_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.bigtable.v2.BigtableProto.internal_static_google_bigtable_v2_SimpleExecuteQueryResponse_descriptor;
    }

    @java.lang.Override
    public com.google.bigtable.v2.SimpleExecuteQueryResponse getDefaultInstanceForType() {
      return com.google.bigtable.v2.SimpleExecuteQueryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.bigtable.v2.SimpleExecuteQueryResponse build() {
      com.google.bigtable.v2.SimpleExecuteQueryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.bigtable.v2.SimpleExecuteQueryResponse buildPartial() {
      com.google.bigtable.v2.SimpleExecuteQueryResponse result = new com.google.bigtable.v2.SimpleExecuteQueryResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.bigtable.v2.SimpleExecuteQueryResponse result) {
      if (rowsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.rows_ = rows_;
      } else {
        result.rows_ = rowsBuilder_.build();
      }
    }

    private void buildPartial0(com.google.bigtable.v2.SimpleExecuteQueryResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.schema_ = schemaBuilder_ == null
            ? schema_
            : schemaBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nextPageToken_ = nextPageToken_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.bigtable.v2.SimpleExecuteQueryResponse) {
        return mergeFrom((com.google.bigtable.v2.SimpleExecuteQueryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.bigtable.v2.SimpleExecuteQueryResponse other) {
      if (other == com.google.bigtable.v2.SimpleExecuteQueryResponse.getDefaultInstance()) return this;
      if (other.hasSchema()) {
        mergeSchema(other.getSchema());
      }
      if (rowsBuilder_ == null) {
        if (!other.rows_.isEmpty()) {
          if (rows_.isEmpty()) {
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRowsIsMutable();
            rows_.addAll(other.rows_);
          }
          onChanged();
        }
      } else {
        if (!other.rows_.isEmpty()) {
          if (rowsBuilder_.isEmpty()) {
            rowsBuilder_.dispose();
            rowsBuilder_ = null;
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
            rowsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetRowsFieldBuilder() : null;
          } else {
            rowsBuilder_.addAllMessages(other.rows_);
          }
        }
      }
      if (!other.getNextPageToken().isEmpty()) {
        nextPageToken_ = other.nextPageToken_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetSchemaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.bigtable.v2.ArrayValue m =
                  input.readMessage(
                      com.google.bigtable.v2.ArrayValue.parser(),
                      extensionRegistry);
              if (rowsBuilder_ == null) {
                ensureRowsIsMutable();
                rows_.add(m);
              } else {
                rowsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              nextPageToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.bigtable.v2.ProtoSchema schema_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.bigtable.v2.ProtoSchema, com.google.bigtable.v2.ProtoSchema.Builder, com.google.bigtable.v2.ProtoSchemaOrBuilder> schemaBuilder_;
    /**
     * <pre>
     * Schema of the columns in the result set.
     * </pre>
     *
     * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
     * @return Whether the schema field is set.
     */
    public boolean hasSchema() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Schema of the columns in the result set.
     * </pre>
     *
     * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
     * @return The schema.
     */
    public com.google.bigtable.v2.ProtoSchema getSchema() {
      if (schemaBuilder_ == null) {
        return schema_ == null ? com.google.bigtable.v2.ProtoSchema.getDefaultInstance() : schema_;
      } else {
        return schemaBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Schema of the columns in the result set.
     * </pre>
     *
     * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
     */
    public Builder setSchema(com.google.bigtable.v2.ProtoSchema value) {
      if (schemaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        schema_ = value;
      } else {
        schemaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema of the columns in the result set.
     * </pre>
     *
     * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
     */
    public Builder setSchema(
        com.google.bigtable.v2.ProtoSchema.Builder builderForValue) {
      if (schemaBuilder_ == null) {
        schema_ = builderForValue.build();
      } else {
        schemaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema of the columns in the result set.
     * </pre>
     *
     * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
     */
    public Builder mergeSchema(com.google.bigtable.v2.ProtoSchema value) {
      if (schemaBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          schema_ != null &&
          schema_ != com.google.bigtable.v2.ProtoSchema.getDefaultInstance()) {
          getSchemaBuilder().mergeFrom(value);
        } else {
          schema_ = value;
        }
      } else {
        schemaBuilder_.mergeFrom(value);
      }
      if (schema_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Schema of the columns in the result set.
     * </pre>
     *
     * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
     */
    public Builder clearSchema() {
      bitField0_ = (bitField0_ & ~0x00000001);
      schema_ = null;
      if (schemaBuilder_ != null) {
        schemaBuilder_.dispose();
        schemaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema of the columns in the result set.
     * </pre>
     *
     * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
     */
    public com.google.bigtable.v2.ProtoSchema.Builder getSchemaBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetSchemaFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Schema of the columns in the result set.
     * </pre>
     *
     * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
     */
    public com.google.bigtable.v2.ProtoSchemaOrBuilder getSchemaOrBuilder() {
      if (schemaBuilder_ != null) {
        return schemaBuilder_.getMessageOrBuilder();
      } else {
        return schema_ == null ?
            com.google.bigtable.v2.ProtoSchema.getDefaultInstance() : schema_;
      }
    }
    /**
     * <pre>
     * Schema of the columns in the result set.
     * </pre>
     *
     * <code>.google.bigtable.v2.ProtoSchema schema = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.bigtable.v2.ProtoSchema, com.google.bigtable.v2.ProtoSchema.Builder, com.google.bigtable.v2.ProtoSchemaOrBuilder> 
        internalGetSchemaFieldBuilder() {
      if (schemaBuilder_ == null) {
        schemaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.bigtable.v2.ProtoSchema, com.google.bigtable.v2.ProtoSchema.Builder, com.google.bigtable.v2.ProtoSchemaOrBuilder>(
                getSchema(),
                getParentForChildren(),
                isClean());
        schema_ = null;
      }
      return schemaBuilder_;
    }

    private java.util.List<com.google.bigtable.v2.ArrayValue> rows_ =
      java.util.Collections.emptyList();
    private void ensureRowsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        rows_ = new java.util.ArrayList<com.google.bigtable.v2.ArrayValue>(rows_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.bigtable.v2.ArrayValue, com.google.bigtable.v2.ArrayValue.Builder, com.google.bigtable.v2.ArrayValueOrBuilder> rowsBuilder_;

    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public java.util.List<com.google.bigtable.v2.ArrayValue> getRowsList() {
      if (rowsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rows_);
      } else {
        return rowsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public int getRowsCount() {
      if (rowsBuilder_ == null) {
        return rows_.size();
      } else {
        return rowsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public com.google.bigtable.v2.ArrayValue getRows(int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);
      } else {
        return rowsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public Builder setRows(
        int index, com.google.bigtable.v2.ArrayValue value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.set(index, value);
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public Builder setRows(
        int index, com.google.bigtable.v2.ArrayValue.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.set(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public Builder addRows(com.google.bigtable.v2.ArrayValue value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public Builder addRows(
        int index, com.google.bigtable.v2.ArrayValue value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(index, value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public Builder addRows(
        com.google.bigtable.v2.ArrayValue.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public Builder addRows(
        int index, com.google.bigtable.v2.ArrayValue.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public Builder addAllRows(
        java.lang.Iterable<? extends com.google.bigtable.v2.ArrayValue> values) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rows_);
        onChanged();
      } else {
        rowsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public Builder clearRows() {
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        rowsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public Builder removeRows(int index) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.remove(index);
        onChanged();
      } else {
        rowsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public com.google.bigtable.v2.ArrayValue.Builder getRowsBuilder(
        int index) {
      return internalGetRowsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public com.google.bigtable.v2.ArrayValueOrBuilder getRowsOrBuilder(
        int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);  } else {
        return rowsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public java.util.List<? extends com.google.bigtable.v2.ArrayValueOrBuilder> 
         getRowsOrBuilderList() {
      if (rowsBuilder_ != null) {
        return rowsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rows_);
      }
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public com.google.bigtable.v2.ArrayValue.Builder addRowsBuilder() {
      return internalGetRowsFieldBuilder().addBuilder(
          com.google.bigtable.v2.ArrayValue.getDefaultInstance());
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public com.google.bigtable.v2.ArrayValue.Builder addRowsBuilder(
        int index) {
      return internalGetRowsFieldBuilder().addBuilder(
          index, com.google.bigtable.v2.ArrayValue.getDefaultInstance());
    }
    /**
     * <pre>
     * The rows in the result set wherein each row contains values with schema
     * matching the `schema` field above.
     * </pre>
     *
     * <code>repeated .google.bigtable.v2.ArrayValue rows = 2;</code>
     */
    public java.util.List<com.google.bigtable.v2.ArrayValue.Builder> 
         getRowsBuilderList() {
      return internalGetRowsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.bigtable.v2.ArrayValue, com.google.bigtable.v2.ArrayValue.Builder, com.google.bigtable.v2.ArrayValueOrBuilder> 
        internalGetRowsFieldBuilder() {
      if (rowsBuilder_ == null) {
        rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.bigtable.v2.ArrayValue, com.google.bigtable.v2.ArrayValue.Builder, com.google.bigtable.v2.ArrayValueOrBuilder>(
                rows_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        rows_ = null;
      }
      return rowsBuilder_;
    }

    private java.lang.Object nextPageToken_ = "";
    /**
     * <pre>
     * Optional. A token that can be sent as `page_token` to retrieve the next
     * rows in the result set. If this field is omitted, there are no subsequent
     * rows.
     * </pre>
     *
     * <code>string next_page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return The nextPageToken.
     */
    public java.lang.String getNextPageToken() {
      java.lang.Object ref = nextPageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextPageToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. A token that can be sent as `page_token` to retrieve the next
     * rows in the result set. If this field is omitted, there are no subsequent
     * rows.
     * </pre>
     *
     * <code>string next_page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return The bytes for nextPageToken.
     */
    public com.google.protobuf.ByteString
        getNextPageTokenBytes() {
      java.lang.Object ref = nextPageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextPageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. A token that can be sent as `page_token` to retrieve the next
     * rows in the result set. If this field is omitted, there are no subsequent
     * rows.
     * </pre>
     *
     * <code>string next_page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nextPageToken_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. A token that can be sent as `page_token` to retrieve the next
     * rows in the result set. If this field is omitted, there are no subsequent
     * rows.
     * </pre>
     *
     * <code>string next_page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearNextPageToken() {
      nextPageToken_ = getDefaultInstance().getNextPageToken();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. A token that can be sent as `page_token` to retrieve the next
     * rows in the result set. If this field is omitted, there are no subsequent
     * rows.
     * </pre>
     *
     * <code>string next_page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The bytes for nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nextPageToken_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.bigtable.v2.SimpleExecuteQueryResponse)
  }

  // @@protoc_insertion_point(class_scope:google.bigtable.v2.SimpleExecuteQueryResponse)
  private static final com.google.bigtable.v2.SimpleExecuteQueryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.bigtable.v2.SimpleExecuteQueryResponse();
  }

  public static com.google.bigtable.v2.SimpleExecuteQueryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SimpleExecuteQueryResponse>
      PARSER = new com.google.protobuf.AbstractParser<SimpleExecuteQueryResponse>() {
    @java.lang.Override
    public SimpleExecuteQueryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SimpleExecuteQueryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SimpleExecuteQueryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.bigtable.v2.SimpleExecuteQueryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

