// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/session.proto
// Protobuf Java Version: 4.33.6

package com.google.bigtable.v2;

@com.google.protobuf.Generated
public interface TelemetryConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.TelemetryConfiguration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Selector for the debug counters that should be uploaded.
   * </pre>
   *
   * <code>.google.bigtable.v2.TelemetryConfiguration.Level debug_tag_level = 1;</code>
   * @return The enum numeric value on the wire for debugTagLevel.
   */
  int getDebugTagLevelValue();
  /**
   * <pre>
   * Selector for the debug counters that should be uploaded.
   * </pre>
   *
   * <code>.google.bigtable.v2.TelemetryConfiguration.Level debug_tag_level = 1;</code>
   * @return The debugTagLevel.
   */
  com.google.bigtable.v2.TelemetryConfiguration.Level getDebugTagLevel();
}
