syntax = "proto3";

package google.bigtable.v2;

import "storage/datapol/annotations/proto/semantic_annotations.proto";

option go_api_flag = "OPEN_TO_OPAQUE_HYBRID";
option csharp_namespace = "Google.Cloud.Bigtable.V2";
option php_namespace = "Google\\Cloud\\Bigtable\\V2";
option ruby_package = "Google::Cloud::Bigtable::V2";
option java_multiple_files = true;
option java_package = "com.google.bigtable.v2";
option java_outer_classname = "PeerInfoProto";

// PeerInfo contains information about the peer that the client is
// connecting to.
//
// (-- Next ID: 7 --)
message PeerInfo {
  // An opaque identifier for the Google Frontend which serviced this request.
  // Only set when not using DirectAccess.
  int64 google_frontend_id = 1 [(datapol.semantic_type) = ST_NOT_REQUIRED];

  // An opaque identifier for the application frontend which serviced this
  // request.
  int64 application_frontend_id = 2 [(datapol.semantic_type) = ST_NOT_REQUIRED];

  // The Cloud region of the application frontend that served this request.
  string application_frontend_region = 6
      [(datapol.semantic_type) = ST_NOT_REQUIRED];

  // The Cloud zone of the application frontend that served this request.
  string application_frontend_zone = 3
      [deprecated = true, (datapol.semantic_type) = ST_NOT_REQUIRED];

  // The subzone of the application frontend that served this request, e.g. an
  // identifier for where within a zone (within the reported region) the
  // application frontend is.
  string application_frontend_subzone = 4
      [(datapol.semantic_type) = ST_NOT_REQUIRED];

  // The transport type that the client used to connect to this peer.
  enum TransportType {
    // The transport type is unknown.
    TRANSPORT_TYPE_UNKNOWN = 0;
    // The client connected to this peer via an external network
    // (e.g. outside Google Cloud).
    TRANSPORT_TYPE_EXTERNAL = 1;
    // The client connected to this peer via CloudPath.
    TRANSPORT_TYPE_CLOUD_PATH = 2;
    // The client connected to this peer via DirectAccess.
    TRANSPORT_TYPE_DIRECT_ACCESS = 3;
    // The client connected to this peer via Bigtable Sessions using an unknown
    // transport type.
    TRANSPORT_TYPE_SESSION_UNKNOWN = 4;
    // The client connected to this peer via Bigtable Sessions on an external
    // network (e.g. outside Google Cloud).
    TRANSPORT_TYPE_SESSION_EXTERNAL = 5;
    // The client connected to this peer via Bigtable Sessions using CloudPath.
    TRANSPORT_TYPE_SESSION_CLOUD_PATH = 6;
    // The client connected to this peer via Bigtable Sessions using
    // DirectAccess.
    TRANSPORT_TYPE_SESSION_DIRECT_ACCESS = 7;
  }
  TransportType transport_type = 5 [(datapol.semantic_type) = ST_NOT_REQUIRED];
}